AnimationPointers:
	table_width 2, AnimationPointers
	dw SubminoAnimation
	dw SubzillaAnimation
	dw SubzilanteAnimation
	dw GrassnipAnimation
	dw LopsoilAnimation
	dw HaerazorAnimation
	dw CubburnAnimation
	dw CoaldiakAnimation
	dw GrillzlyAnimation
	dw HippourAnimation
	dw DrippourAnimation
	dw HiptorrentAnimation
	dw HamselAnimation
	dw GuinapiAnimation
	dw OpossterAnimation
	dw PossumusAnimation
	dw AxalitlAnimation
	dw AxalotAnimation
	dw HopstotAnimation
	dw LocutsAnimation
	dw ChawpperAnimation
	dw SnolipoliAnimation
	dw CrystalisAnimation
	dw HailothAnimation
	dw TeakbeakAnimation
	dw WoodrillAnimation
	dw FowlletAnimation
	dw FlockshotAnimation
	dw QartridgeAnimation
	dw LouspoutAnimation
	dw ClinchitonAnimation
	dw SkardineAnimation
	dw SkargarosAnimation
	dw SpikidnaAnimation
	dw EchlipseAnimation
	dw EchneedoAnimation
	dw KitteryAnimation
	dw FeliteAnimation
	dw FelectricAnimation
	dw HiszardAnimation
	dw RepvialAnimation
	dw KomodoseAnimation
	dw CursiorAnimation
	dw EnvoilAnimation
	dw NavitarAnimation
	dw SlickreteAnimation
	dw GasphaltAnimation
	dw IngrovertAnimation
	dw FriteshadeAnimation
	dw BugglarAnimation
	dw SpydarAnimation
	dw PorcelionAnimation
	dw FuumaAnimation
	dw WallopyAnimation
	dw JabarooAnimation
	dw OrizuruAnimation
	dw OrigeronAnimation
	dw BinarsAnimation
	dw BushidudeAnimation
	dw SinistarAnimation
	dw DronnelAnimation
	dw RumblebeeAnimation
	dw BagroundAnimation
	dw TerragerAnimation
	dw CauldegarAnimation
	dw RockadeAnimation
	dw BarrockAnimation
	dw MarblockAnimation
	dw SliverfishAnimation
	dw ReddotAnimation
	dw PolkapixAnimation
	dw ImpanAnimation
	dw DaetyrAnimation
	dw DaemoonAnimation
	dw SabarinthAnimation
	dw BombardleAnimation
	dw AntennianAnimation
	dw OkapsiAnimation
	dw TelekapiAnimation
	dw KaiyakAnimation
	dw SurfalloAnimation
	dw HemogoblinAnimation
	dw PlatapoxAnimation
	dw PlatyrusAnimation
	dw SearlingAnimation
	dw FlaribouAnimation
	dw MarskratAnimation
	dw CatybaraAnimation
	dw CrescaldoAnimation
	dw PescaldoAnimation
	dw PlumplingAnimation
	dw LeapearAnimation
	dw LeviathornAnimation
	dw StrawrbleAnimation
	dw StrawmerriAnimation
	dw StrawmenadAnimation
	dw PampoochSAnimation
	dw PampodourSAnimation
	dw PampoochPAnimation
	dw PampodourPAnimation
	dw PampoochTAnimation 
	dw PampodourTAnimation
	dw TutsweetAnimation
	dw TutufruttiAnimation
	dw ScrumshefAnimation
	dw SousfleAnimation
	dw ApasheeAnimation
	dw CommansheeAnimation
	dw DittoAnimation
	dw ConstaboldAnimation
	dw TarotisAnimation
	dw OrchantisAnimation
	dw HocupocusAnimation
	dw PresticianAnimation
	dw DoracleAnimation
	dw DelphoraAnimation
	dw XsailerateAnimation
	dw DiviperAnimation
	dw SnorcobraAnimation
	dw EspungeAnimation
	dw ZiggrathAnimation
	dw CanvalogAnimation
	dw PlasmanianAnimation
	dw CladilloAnimation
	dw ArmordilloAnimation
	dw CloakroakAnimation
	dw CamoufraugAnimation
	dw MirauggerAnimation
	dw MagikarpAnimation
	dw GyaradosAnimation
	dw LaprasAnimation
	dw KoffingAnimation
	dw EeveeAnimation
	dw VaporeonAnimation
	dw JolteonAnimation
	dw FlareonAnimation
	dw PorygonAnimation
	dw OmanyteAnimation
	dw OmastarAnimation
	dw KabutoAnimation
	dw KabutopsAnimation
	dw AerodactylAnimation
	dw SnorlaxAnimation
	dw ArticunoAnimation
	dw ZapdosAnimation
	dw MoltresAnimation
	dw DratiniAnimation
	dw DragonairAnimation
	dw DragoniteAnimation
	dw MewtwoAnimation
	dw MewAnimation
	dw ChikoritaAnimation
	dw BayleefAnimation
	dw MeganiumAnimation
	dw CyndaquilAnimation
	dw QuilavaAnimation
	dw TyphlosionAnimation
	dw TotodileAnimation
	dw CroconawAnimation
	dw FeraligatrAnimation
	dw SentretAnimation
	dw FurretAnimation
	dw HoothootAnimation
	dw NoctowlAnimation
	dw LedybaAnimation
	dw LedianAnimation
	dw SpinarakAnimation
	dw AriadosAnimation
	dw CrobatAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw PichuAnimation
	dw CleffaAnimation
	dw IgglybuffAnimation
	dw TogepiAnimation
	dw TogeticAnimation
	dw NatuAnimation
	dw XatuAnimation
	dw MareepAnimation
	dw FlaaffyAnimation
	dw AmpharosAnimation
	dw BellossomAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw SudowoodoAnimation
	dw PolitoedAnimation
	dw HoppipAnimation
	dw SkiploomAnimation
	dw JumpluffAnimation
	dw AipomAnimation
	dw SunkernAnimation
	dw SunfloraAnimation
	dw YanmaAnimation
	dw WooperAnimation
	dw QuagsireAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw MurkrowAnimation
	dw SlowkingAnimation
	dw MisdreavusAnimation
	dw UnownAnimation
	dw WobbuffetAnimation
	dw GirafarigAnimation
	dw PinecoAnimation
	dw ForretressAnimation
	dw DunsparceAnimation
	dw GligarAnimation
	dw SteelixAnimation
	dw SnubbullAnimation
	dw GranbullAnimation
	dw QwilfishAnimation
	dw ScizorAnimation
	dw ShuckleAnimation
	dw HeracrossAnimation
	dw SneaselAnimation
	dw TeddiursaAnimation
	dw UrsaringAnimation
	dw SlugmaAnimation
	dw MagcargoAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw CorsolaAnimation
	dw RemoraidAnimation
	dw OctilleryAnimation
	dw DelibirdAnimation
	dw MantineAnimation
	dw SkarmoryAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw KingdraAnimation
	dw PhanpyAnimation
	dw DonphanAnimation
	dw Porygon2Animation
	dw StantlerAnimation
	dw SmeargleAnimation
	dw TyrogueAnimation
	dw HitmontopAnimation
	dw SmoochumAnimation
	dw ElekidAnimation
	dw MagbyAnimation
	dw MiltankAnimation
	dw BlisseyAnimation
	dw RaikouAnimation
	dw EnteiAnimation
	dw SuicuneAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw LugiaAnimation
	dw HoOhAnimation
	dw CelebiAnimation
	assert_table_length NUM_POKEMON
