AnimationPointers:
	table_width 2, AnimationPointers
	dw SubminoAnimation
	dw SubzillaAnimation
	dw SubzilanteAnimation
	dw GrassnipAnimation
	dw LopsoilAnimation
	dw HaerazorAnimation
	dw CubburnAnimation
	dw CoaldiakAnimation
	dw GrillzlyAnimation
	dw HippourAnimation
	dw DrippourAnimation
	dw HiptorrentAnimation
	dw HamselAnimation
	dw GuinapiAnimation
	dw OpossterAnimation
	dw PossumusAnimation
	dw AxalitlAnimation
	dw AxalotAnimation
	dw HopstotAnimation
	dw LocutsAnimation
	dw ChawpperAnimation
	dw SnolipoliAnimation
	dw CrystalisAnimation
	dw HailothAnimation
	dw TeakbeakAnimation
	dw WoodrillAnimation
	dw FowlletAnimation
	dw FlockshotAnimation
	dw QartridgeAnimation
	dw LouspoutAnimation
	dw ClinchitonAnimation
	dw SkardineAnimation
	dw SkargarosAnimation
	dw SpikidnaAnimation
	dw EchlipseAnimation
	dw EchneedoAnimation
	dw KitteryAnimation
	dw FeliteAnimation
	dw FelectricAnimation
	dw HiszardAnimation
	dw RepvialAnimation
	dw KomodoseAnimation
	dw CursiorAnimation
	dw EnvoilAnimation
	dw NavitarAnimation
	dw SlickreteAnimation
	dw GasphaltAnimation
	dw IngrovertAnimation
	dw FriteshadeAnimation
	dw BugglarAnimation
	dw SpydarAnimation
	dw PorcelionAnimation
	dw FuumaAnimation
	dw WallopyAnimation
	dw JabarooAnimation
	dw OrizuruAnimation
	dw OrigeronAnimation
	dw BinarsAnimation
	dw BushidudeAnimation
	dw SinistarAnimation
	dw DronnelAnimation
	dw RumblebeeAnimation
	dw BagroundAnimation
	dw TerragerAnimation
	dw CauldegarAnimation
	dw RockadeAnimation
	dw BarrockAnimation
	dw MarblockAnimation
	dw SliverfishAnimation
	dw ReddotAnimation
	dw PolkapixAnimation
	dw ImpanAnimation
	dw DaetyrAnimation
	dw DaemoonAnimation
	dw SabarinthAnimation
	dw BombardleAnimation
	dw AntennianAnimation
	dw OkapsiAnimation
	dw TelekapiAnimation
	dw KaiyakAnimation
	dw SurfalloAnimation
	dw HemogoblinAnimation
	dw PlatapoxAnimation
	dw PlatyrusAnimation
	dw SearlingAnimation
	dw FlaribouAnimation
	dw MarskratAnimation
	dw CatybaraAnimation
	dw CrescaldoAnimation
	dw PescaldoAnimation
	dw PlumplingAnimation
	dw LeapearAnimation
	dw LeviathornAnimation
	dw StrawrbleAnimation
	dw StrawmerriAnimation
	dw StrawmenadAnimation
	dw PampoochSAnimation
	dw PampodourSAnimation
	dw PampoochPAnimation
	dw PampodourPAnimation
	dw PampoochTAnimation 
	dw PampodourTAnimation
	dw TutsweetAnimation
	dw TutufruttiAnimation
	dw ScrumshefAnimation
	dw SousfleAnimation
	dw ApasheeAnimation
	dw CommansheeAnimation
	dw DittoAnimation
	dw ConstaboldAnimation
	dw TarotisAnimation
	dw OrchantisAnimation
	dw HocupocusAnimation
	dw PresticianAnimation
	dw DoracleAnimation
	dw DelphoraAnimation
	dw XsailerateAnimation
	dw DiviperAnimation
	dw SnorcobraAnimation
	dw EspungeAnimation
	dw ZiggrathAnimation
	dw CanvalogAnimation
	dw PlasmanianAnimation
	dw CladilloAnimation
	dw ArmordilloAnimation
	dw CloakroakAnimation
	dw CamoufraugAnimation
	dw MirauggerAnimation
	dw TrubbleAnimation
	dw GolgraniteAnimation
	dw SwinedelAnimation
	dw ColomentalAnimation
	dw ElecmentalAnimation
	dw OccumentalAnimation
	dw SedimentalAnimation
	dw GaiamentalAnimation
	dw IgnimentalAnimation
	dw MolumentalAnimation
	dw VilementalAnimation
	dw AlumentalAnimation
	dw SalamentalAnimation
	dw FarimentalAnimation
	dw CtrlbotAnimation
	dw AltbotAnimation
	dw DelbotAnimation
	dw PummatAnimation
	dw TraumatAnimation
	dw AcromatAnimation
	dw ParagodaAnimation
	dw DoomstoneAnimation
	dw FeartressAnimation
	dw GothedralAnimation
	dw TsukimikoAnimation
	dw ZonbiAnimation
	dw SmokaiAnimation
	dw TrollgoreAnimation
	dw GexelAnimation
	dw RenderexeAnimation
	dw SuniataAnimation
	dw HapsukaAnimation
	dw DardukaAnimation
	dw StoatsdoolAnimation
	dw ManifistAnimation
	dw GhauntedAnimation
	dw HazvatAnimation
	dw ToxivatAnimation
	dw NarburrAnimation
	dw NarcicleAnimation
	dw PlanktoonAnimation
	dw AguamarineAnimation
	dw CiriousAnimation
	dw ZephluffAnimation
	dw NimbillowAnimation
	dw FafnareAnimation
	dw DreigloreAnimation
	dw BambootemAnimation
	dw FlorascentAnimation
	dw ThissileAnimation
	dw ElecoilAnimation
	dw WattvernAnimation
	dw ThundrakeAnimation
	dw EctopusAnimation
	dw SwirrelAnimation
	dw AlpackAnimation
	dw LlamiceAnimation
	dw FenriftAnimation
	dw GlaewulfAnimation
	dw SlomeAnimation
	dw DwarftainAnimation
	dw YodeleiAnimation
	dw BivalryAnimation
	dw ConchorallAnimation
	dw ColoshellAnimation
	dw MogulluskAnimation
	dw TusselAnimation
	dw BibbonAnimation
	dw BuffboonAnimation
	dw BanandrillAnimation
	dw KwombatAnimation
	dw PillanteAnimation
	dw RolldierAnimation
	dw AntrenchDAnimation
	dw LagoopAnimation
	dw TarmoorAnimation
	dw MiasmireAnimation
	dw GonzaiAnimation
	dw TikitoaAnimation
	dw TikiwickiAnimation
	dw VinkingAnimation
	dw SheergonAnimation
	dw SworgonAnimation
	dw ParrodisoAnimation
	dw PollirojerAnimation
	dw FlamamigoAnimation
	dw CassavageAnimation
	dw HarpshootrAnimation
	dw CuraribriAnimation
	dw CocapitanAnimation
	dw TecnocerosAnimation
	dw MedisprateAnimation
	dw AardvoliAnimation
	dw EntrapmonAnimation
	dw GhiardoraAnimation
	dw OctilleryAnimation
	dw DelibirdAnimation
	dw MantineAnimation
	dw SkarmoryAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw KingdraAnimation
	dw PhanpyAnimation
	dw DonphanAnimation
	dw OmanyteAnimation
	dw OmastarAnimation
	dw KabutoAnimation
	dw KabutopsAnimation
	dw HitmontopAnimation
	dw SmoochumAnimation
	dw ElekidAnimation
	dw MagbyAnimation
	dw MiltankAnimation
	dw BlisseyAnimation
	dw RaikouAnimation
	dw EnteiAnimation
	dw SuicuneAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw LugiaAnimation
	dw HoOhAnimation
	dw CelebiAnimation
	dw UnownAnimation
	assert_table_length NUM_POKEMON
