BitmasksPointers:
	table_width 2, BitmasksPointers
	dw SubminoBitmasks
	dw SubzillaBitmasks
	dw SubzilanteBitmasks
	dw GrassnipBitmasks
	dw LopsoilBitmasks
	dw HaerazorBitmasks
	dw CubburnBitmasks
	dw CoaldiakBitmasks
	dw GrillzlyBitmasks
	dw HippourBitmasks
	dw DrippourBitmasks
	dw HiptorrentBitmasks
	dw HamselBitmasks
	dw GuinapiBitmasks
	dw OpossterBitmasks
	dw PossumusBitmasks
	dw AxalitlBitmasks
	dw AxalotBitmasks
	dw HopstotBitmasks
	dw LocutsBitmasks
	dw ChawpperBitmasks
	dw SnolipoliBitmasks
	dw CrystalisBitmasks
	dw HailothBitmasks
	dw TeakbeakBitmasks
	dw WoodrillBitmasks
	dw FowlletBitmasks
	dw FlockshotBitmasks
	dw QartridgeBitmasks
	dw LouspoutBitmasks
	dw ClinchitonBitmasks
	dw SkardineBitmasks
	dw SkargarosBitmasks
	dw SpikidnaBitmasks
	dw EchlipseBitmasks
	dw EchneedoBitmasks
	dw KitteryBitmasks
	dw FeliteBitmasks
	dw FelectricBitmasks
	dw HiszardBitmasks
	dw RepvialBitmasks
	dw KomodoseBitmasks
	dw CursiorBitmasks
	dw EnvoilBitmasks
	dw NavitarBitmasks
	dw SlickreteBitmasks
	dw GasphaltBitmasks
	dw IngrovertBitmasks
	dw FriteshadeBitmasks
	dw BugglarBitmasks
	dw SpydarBitmasks
	dw PorcelionBitmasks
	dw FuumaBitmasks
	dw WallopyBitmasks
	dw JabarooBitmasks
	dw OrizuruBitmasks
	dw OrigeronBitmasks
	dw BinarsBitmasks
	dw BushidudeBitmasks
	dw SinistarBitmasks
	dw DronnelBitmasks
	dw RumblebeeBitmasks
	dw BagroundBitmasks
	dw TerragerBitmasks
	dw CauldegarBitmasks
	dw RockadeBitmasks
	dw BarrockBitmasks
	dw MarblockBitmasks
	dw SliverfishBitmasks
	dw ReddotBitmasks
	dw PolkapixBitmasks
	dw ImpanBitmasks
	dw DaetyrBitmasks
	dw DaemoonBitmasks
	dw SabarinthBitmasks
	dw BombardleBitmasks
	dw AntennianBitmasks
	dw OkapsiBitmasks
	dw TelekapiBitmasks
	dw KaiyakBitmasks
	dw SurfalloBitmasks
	dw HemogoblinBitmasks
	dw PlatapoxBitmasks
	dw PlatyrusBitmasks
	dw SearlingBitmasks
	dw FlaribouBitmasks
	dw MarskratBitmasks
	dw CatybaraBitmasks
	dw CrescaldoBitmasks
	dw PescaldoBitmasks
	dw PlumplingBitmasks
	dw LeapearBitmasks
	dw LeviathornBitmasks
	dw StrawrbleBitmasks
	dw StrawmerriBitmasks
	dw StrawmenadBitmasks
	dw PampoochSBitmasks
	dw PampodourSBitmasks
	dw PampoochPBitmasks
	dw PampodourPBitmasks
	dw PampoochTBitmasks
	dw PampodourTBitmasks
	dw TutsweetBitmasks	
	dw TutufruttiBitmasks
	dw ScrumshefBitmasks
	dw SousfleBitmasks
	dw ApasheeBitmasks
	dw CommansheeBitmasks
	dw DittoBitmasks
	dw ConstaboldBitmasks
	dw TarotisBitmasks
	dw OrchantisBitmasks
	dw HocupocusBitmasks
	dw PresticianBitmasks
	dw DoracleBitmasks
	dw DelphoraBitmasks
	dw XsailerateBitmasks
	dw DiviperBitmasks
	dw SnorcobraBitmasks
	dw EspungeBitmasks
	dw ZiggrathBitmasks
	dw CanvalogBitmasks
	dw PlasmanianBitmasks
	dw CladilloBitmasks
	dw ArmordilloBitmasks
	dw CloakroakBitmasks
	dw CamoufraugBitmasks
	dw MirauggerBitmasks
	dw TrubbleBitmasks
	dw GolgraniteBitmasks
	dw SwinedelBitmasks
	dw ColomentalBitmasks
	dw ElecmentalBitmasks
	dw OccumentalBitmasks
	dw SedimentalBitmasks
	dw GaiamentalBitmasks
	dw IgnimentalBitmasks
	dw MolumentalBitmasks
	dw VilementalBitmasks
	dw AlumentalBitmasks
	dw SalamentalBitmasks
	dw FarimentalBitmasks
	dw CtrlbotBitmasks
	dw AltbotBitmasks
	dw DelbotBitmasks
	dw PummatBitmasks
	dw TraumatBitmasks
	dw AcromatBitmasks
	dw ParagodaBitmasks
	dw DoomstoneBitmasks
	dw FeartressBitmasks
	dw GothedralBitmasks
	dw TsukimikoBitmasks
	dw ZonbiBitmasks
	dw SmokaiBitmasks
	dw TrollgoreBitmasks
	dw GexelBitmasks
	dw RenderexeBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw SentretBitmasks
	dw FurretBitmasks
	dw HoothootBitmasks
	dw NoctowlBitmasks
	dw LedybaBitmasks
	dw LedianBitmasks
	dw SpinarakBitmasks
	dw AriadosBitmasks
	dw CrobatBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw PichuBitmasks
	dw CleffaBitmasks
	dw IgglybuffBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw NatuBitmasks
	dw XatuBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw BellossomBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw SudowoodoBitmasks
	dw PolitoedBitmasks
	dw HoppipBitmasks
	dw SkiploomBitmasks
	dw JumpluffBitmasks
	dw AipomBitmasks
	dw SunkernBitmasks
	dw SunfloraBitmasks
	dw YanmaBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw MurkrowBitmasks
	dw SlowkingBitmasks
	dw MisdreavusBitmasks
	dw UnownBitmasks
	dw WobbuffetBitmasks
	dw GirafarigBitmasks
	dw PinecoBitmasks
	dw ForretressBitmasks
	dw DunsparceBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw SnubbullBitmasks
	dw GranbullBitmasks
	dw QwilfishBitmasks
	dw ScizorBitmasks
	dw ShuckleBitmasks
	dw HeracrossBitmasks
	dw SneaselBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw CorsolaBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw DelibirdBitmasks
	dw MantineBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw OmanyteBitmasks
	dw OmastarBitmasks
	dw KabutoBitmasks
	dw KabutopsBitmasks
	dw HitmontopBitmasks
	dw SmoochumBitmasks
	dw ElekidBitmasks
	dw MagbyBitmasks
	dw MiltankBitmasks
	dw BlisseyBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	assert_table_length NUM_POKEMON
