FramesPointers:
	table_width 2, FramesPointers
	dw SubminoFrames
	dw SubzillaFrames
	dw SubzilanteFrames
	dw GrassnipFrames
	dw LopsoilFrames
	dw HaerazorFrames
	dw CubburnFrames
	dw CoaldiakFrames
	dw GrillzlyFrames
	dw HippourFrames
	dw DrippourFrames
	dw HiptorrentFrames
	dw HamselFrames
	dw GuinapiFrames
	dw OpossterFrames
	dw PossumusFrames
	dw AxalitlFrames
	dw AxalotFrames
	dw HopstotFrames
	dw LocutsFrames
	dw ChawpperFrames
	dw SnolipoliFrames
	dw CrystalisFrames
	dw HailothFrames
	dw TeakbeakFrames
	dw WoodrillFrames
	dw FowlletFrames
	dw FlockshotFrames
	dw QartridgeFrames
	dw LouspoutFrames
	dw ClinchitonFrames
	dw SkardineFrames
	dw SkargarosFrames
	dw SpikidnaFrames
	dw EchlipseFrames
	dw EchneedoFrames
	dw KitteryFrames
	dw FeliteFrames
	dw FelectricFrames
	dw HiszardFrames
	dw RepvialFrames
	dw KomodoseFrames
	dw OddishFrames
	dw GloomFrames
	dw VileplumeFrames
	dw ParasFrames
	dw ParasectFrames
	dw VenonatFrames
	dw VenomothFrames
	dw DiglettFrames
	dw DugtrioFrames
	dw MeowthFrames
	dw PersianFrames
	dw PsyduckFrames
	dw GolduckFrames
	dw MankeyFrames
	dw PrimeapeFrames
	dw GrowlitheFrames
	dw ArcanineFrames
	dw PoliwagFrames
	dw PoliwhirlFrames
	dw PoliwrathFrames
	dw AbraFrames
	dw KadabraFrames
	dw AlakazamFrames
	dw MachopFrames
	dw MachokeFrames
	dw MachampFrames
	dw BellsproutFrames
	dw WeepinbellFrames
	dw VictreebelFrames
	dw TentacoolFrames
	dw TentacruelFrames
	dw GeodudeFrames
	dw GravelerFrames
	dw GolemFrames
	dw PonytaFrames
	dw RapidashFrames
	dw SlowpokeFrames
	dw SlowbroFrames
	dw MagnemiteFrames
	dw MagnetonFrames
	dw FarfetchDFrames
	dw DoduoFrames
	dw DodrioFrames
	dw SeelFrames
	dw DewgongFrames
	dw GrimerFrames
	dw MukFrames
	dw ShellderFrames
	dw CloysterFrames
	dw GastlyFrames
	dw HaunterFrames
	dw GengarFrames
	dw OnixFrames
	dw DrowzeeFrames
	dw HypnoFrames
	dw KrabbyFrames
	dw KinglerFrames
	dw VoltorbFrames
	dw ElectrodeFrames
	dw NidoranFFrames
	dw ExeggutorFrames
	dw NidoranMFrames
	dw MarowakFrames
	dw HitmonleeFrames
	dw HitmonchanFrames
	dw LickitungFrames
	dw KoffingFrames
	dw WeezingFrames
	dw RhyhornFrames
	dw RhydonFrames
	dw ChanseyFrames
	dw TangelaFrames
	dw KangaskhanFrames
	dw HorseaFrames
	dw SeadraFrames
	dw GoldeenFrames
	dw SeakingFrames
	dw StaryuFrames
	dw StarmieFrames
	dw MrMimeFrames
	dw ScytherFrames
	dw JynxFrames
	dw ElectabuzzFrames
	dw MagmarFrames
	dw PinsirFrames
	dw TaurosFrames
	dw MagikarpFrames
	dw GyaradosFrames
	dw LaprasFrames
	dw DittoFrames
	dw EeveeFrames
	dw VaporeonFrames
	dw JolteonFrames
	dw FlareonFrames
	dw PorygonFrames
	dw OmanyteFrames
	dw OmastarFrames
	dw KabutoFrames
	dw KabutopsFrames
	dw AerodactylFrames
	dw SnorlaxFrames
	dw ArticunoFrames
	dw ZapdosFrames
	dw MoltresFrames
	dw DratiniFrames
	dw DragonairFrames
	dw DragoniteFrames
	dw MewtwoFrames
	dw MewFrames
	dw ChikoritaFrames
	dw BayleefFrames
	dw MeganiumFrames
	dw CyndaquilFrames
	dw QuilavaFrames
	dw TyphlosionFrames
	dw TotodileFrames
	dw CroconawFrames
	dw FeraligatrFrames
	dw SentretFrames
	dw FurretFrames
	dw HoothootFrames
	dw NoctowlFrames
	dw LedybaFrames
	dw LedianFrames
	dw SpinarakFrames
	dw AriadosFrames
	dw CrobatFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw PichuFrames
	dw CleffaFrames
	dw IgglybuffFrames
	dw TogepiFrames
	dw TogeticFrames
	dw NatuFrames
	dw XatuFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw BellossomFrames
	dw MarillFrames
	dw AzumarillFrames
	dw SudowoodoFrames
	dw PolitoedFrames
	dw HoppipFrames
	dw SkiploomFrames
	dw JumpluffFrames
	dw AipomFrames
	dw SunkernFrames
	dw SunfloraFrames
	dw YanmaFrames
	dw WooperFrames
	dw QuagsireFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw MurkrowFrames
	dw SlowkingFrames
	dw MisdreavusFrames
	dw UnownFrames
	dw WobbuffetFrames
	dw GirafarigFrames
	dw PinecoFrames
	dw ForretressFrames
	dw DunsparceFrames
	dw GligarFrames
	dw SteelixFrames
	dw SnubbullFrames
	dw GranbullFrames
	dw QwilfishFrames
	dw ScizorFrames
	dw ShuckleFrames
	dw HeracrossFrames
	dw SneaselFrames
	dw TeddiursaFrames
	dw UrsaringFrames
	dw SlugmaFrames
	dw MagcargoFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw CorsolaFrames
	dw RemoraidFrames
	dw OctilleryFrames
	dw DelibirdFrames
	dw MantineFrames
	dw SkarmoryFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw KingdraFrames
	dw PhanpyFrames
	dw DonphanFrames
	dw Porygon2Frames
	dw StantlerFrames
	dw SmeargleFrames
	dw TyrogueFrames
	dw HitmontopFrames
	dw SmoochumFrames
	dw ElekidFrames
	dw MagbyFrames
	dw MiltankFrames
	dw BlisseyFrames
	dw RaikouFrames
	dw EnteiFrames
	dw SuicuneFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw LugiaFrames
	dw HoOhFrames
	dw CelebiFrames
	assert_table_length NUM_POKEMON
