FramesPointers:
	table_width 2, FramesPointers
	dw SubminoFrames
	dw SubzillaFrames
	dw SubzilanteFrames
	dw GrassnipFrames
	dw LopsoilFrames
	dw HaerazorFrames
	dw CubburnFrames
	dw CoaldiakFrames
	dw GrillzlyFrames
	dw HippourFrames
	dw DrippourFrames
	dw HiptorrentFrames
	dw HamselFrames
	dw GuinapiFrames
	dw OpossterFrames
	dw PossumusFrames
	dw AxalitlFrames
	dw AxalotFrames
	dw HopstotFrames
	dw LocutsFrames
	dw ChawpperFrames
	dw SnolipoliFrames
	dw CrystalisFrames
	dw HailothFrames
	dw TeakbeakFrames
	dw WoodrillFrames
	dw FowlletFrames
	dw FlockshotFrames
	dw QartridgeFrames
	dw LouspoutFrames
	dw ClinchitonFrames
	dw SkardineFrames
	dw SkargarosFrames
	dw SpikidnaFrames
	dw EchlipseFrames
	dw EchneedoFrames
	dw KitteryFrames
	dw FeliteFrames
	dw FelectricFrames
	dw HiszardFrames
	dw RepvialFrames
	dw KomodoseFrames
	dw CursiorFrames
	dw EnvoilFrames
	dw NavitarFrames
	dw SlickreteFrames
	dw GasphaltFrames
	dw IngrovertFrames
	dw FriteshadeFrames
	dw BugglarFrames
	dw SpydarFrames
	dw PorcelionFrames
	dw FuumaFrames
	dw WallopyFrames
	dw JabarooFrames
	dw OrizuruFrames
	dw OrigeronFrames
	dw BinarsFrames
	dw BushidudeFrames
	dw SinistarFrames
	dw DronnelFrames
	dw RumblebeeFrames
	dw BagroundFrames
	dw TerragerFrames
	dw CauldegarFrames
	dw RockadeFrames
	dw BarrockFrames
	dw MarblockFrames
	dw SliverfishFrames
	dw ReddotFrames
	dw PolkapixFrames
	dw ImpanFrames
	dw DaetyrFrames
	dw DaemoonFrames
	dw SabarinthFrames
	dw BombardleFrames
	dw AntennianFrames
	dw OkapsiFrames
	dw TelekapiFrames
	dw KaiyakFrames
	dw SurfalloFrames
	dw HemogoblinFrames
	dw PlatapoxFrames
	dw PlatyrusFrames
	dw SearlingFrames
	dw FlaribouFrames
	dw MarskratFrames
	dw CatybaraFrames
	dw CrescaldoFrames
	dw PescaldoFrames
	dw PlumplingFrames
	dw LeapearFrames
	dw LeviathornFrames
	dw StrawrbleFrames
	dw StrawmerriFrames
	dw StrawmenadFrames
	dw PampoochSFrames
	dw PampodourSFrames
	dw PampoochPFrames
	dw PampodourPFrames
	dw PampoochTFrames
	dw PampodourTFrames
	dw TutsweetFrames
	dw TutufruttiFrames
	dw ScrumshefFrames
	dw SousfleFrames
	dw ApasheeFrames
	dw CommansheeFrames
	dw DittoFrames
	dw ConstaboldFrames
	dw TarotisFrames
	dw OrchantisFrames
	dw HocupocusFrames
	dw PresticianFrames
	dw DoracleFrames
	dw DelphoraFrames
	dw XsailerateFrames
	dw DiviperFrames
	dw SnorcobraFrames
	dw EspungeFrames
	dw ZiggrathFrames
	dw CanvalogFrames
	dw PlasmanianFrames
	dw CladilloFrames
	dw ArmordilloFrames
	dw CloakroakFrames
	dw CamoufraugFrames
	dw MirauggerFrames
	dw TrubbleFrames
	dw GolgraniteFrames
	dw SwinedelFrames
	dw ColomentalFrames
	dw ElecmentalFrames
	dw OccumentalFrames
	dw SedimentalFrames
	dw GaiamentalFrames
	dw IgnimentalFrames
	dw MolumentalFrames
	dw VilementalFrames
	dw AlumentalFrames
	dw SalamentalFrames
	dw FarimentalFrames
	dw CtrlbotFrames
	dw AltbotFrames
	dw DelbotFrames
	dw PummatFrames
	dw TraumatFrames
	dw AcromatFrames
	dw ParagodaFrames
	dw DoomstoneFrames
	dw FeartressFrames
	dw GothedralFrames
	dw TsukimikoFrames
	dw ZonbiFrames
	dw SmokaiFrames
	dw TrollgoreFrames
	dw GexelFrames
	dw RenderexeFrames
	dw SuniataFrames
	dw HapsukaFrames
	dw DardukaFrames
	dw StoatsdoolFrames
	dw ManifistFrames
	dw GhauntedFrames
	dw HazvatFrames
	dw ToxivatFrames
	dw NarburrFrames
	dw NarcicleFrames
	dw PlanktoonFrames
	dw AguamarineFrames
	dw CiriousFrames
	dw ZephluffFrames
	dw NimbillowFrames
	dw FafnareFrames
	dw DreigloreFrames
	dw BambootemFrames
	dw FlorascentFrames
	dw ThissileFrames
	dw ElecoilFrames
	dw WattvernFrames
	dw ThundrakeFrames
	dw EctopusFrames
	dw SwirrelFrames
	dw AlpackFrames
	dw LlamiceFrames
	dw FenriftFrames
	dw GlaewulfFrames
	dw SlomeFrames
	dw DwarftainFrames
	dw YodeleiFrames
	dw BivalryFrames
	dw ConchorallFrames
	dw ColoshellFrames
	dw MogulluskFrames
	dw TusselFrames
	dw BibbonFrames
	dw BuffboonFrames
	dw BanandrillFrames
	dw KwombatFrames
	dw PillanteFrames
	dw RolldierFrames
	dw AntrenchDFrames
	dw LagoopFrames
	dw TarmoorFrames
	dw MiasmireFrames
	dw GonzaiFrames
	dw TikitoaFrames
	dw TikiwickiFrames
	dw VinkingFrames
	dw SheergonFrames
	dw SworgonFrames
	dw ScizorFrames
	dw ShuckleFrames
	dw HeracrossFrames
	dw SneaselFrames
	dw TeddiursaFrames
	dw UrsaringFrames
	dw SlugmaFrames
	dw MagcargoFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw CorsolaFrames
	dw RemoraidFrames
	dw OctilleryFrames
	dw DelibirdFrames
	dw MantineFrames
	dw SkarmoryFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw KingdraFrames
	dw PhanpyFrames
	dw DonphanFrames
	dw OmanyteFrames
	dw OmastarFrames
	dw KabutoFrames
	dw KabutopsFrames
	dw HitmontopFrames
	dw SmoochumFrames
	dw ElekidFrames
	dw MagbyFrames
	dw MiltankFrames
	dw BlisseyFrames
	dw RaikouFrames
	dw EnteiFrames
	dw SuicuneFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw LugiaFrames
	dw HoOhFrames
	dw CelebiFrames
	dw UnownFrames
	assert_table_length NUM_POKEMON
