AnimationIdlePointers:
	table_width 2, AnimationIdlePointers
	dw SubminoAnimationIdle
	dw SubzillaAnimationIdle
	dw SubzilanteAnimationIdle
	dw GrassnipAnimationIdle
	dw LopsoilAnimationIdle
	dw HaerazorAnimationIdle
	dw CubburnAnimationIdle
	dw CoaldiakAnimationIdle
	dw GrillzlyAnimationIdle
	dw HippourAnimationIdle
	dw DrippourAnimationIdle
	dw HiptorrentAnimationIdle
	dw HamselAnimationIdle
	dw GuinapiAnimationIdle
	dw OpossterAnimationIdle
	dw PossumusAnimationIdle
	dw AxalitlAnimationIdle
	dw AxalotAnimationIdle
	dw HopstotAnimationIdle
	dw LocutsAnimationIdle
	dw ChawpperAnimationIdle
	dw SnolipoliAnimationIdle
	dw CrystalisAnimationIdle
	dw HailothAnimationIdle
	dw TeakbeakAnimationIdle
	dw WoodrillAnimationIdle
	dw FowlletAnimationIdle
	dw FlockshotAnimationIdle
	dw QartridgeAnimationIdle
	dw LouspoutAnimationIdle
	dw ClinchitonAnimationIdle
	dw SkardineAnimationIdle
	dw SkargarosAnimationIdle
	dw SpikidnaAnimationIdle
	dw EchlipseAnimationIdle
	dw EchneedoAnimationIdle
	dw KitteryAnimationIdle
	dw FeliteAnimationIdle
	dw FelectricAnimationIdle
	dw HiszardAnimationIdle
	dw RepvialAnimationIdle
	dw KomodoseAnimationIdle
	dw CursiorAnimationIdle
	dw EnvoilAnimationIdle
	dw NavitarAnimationIdle
	dw SlickreteAnimationIdle
	dw GasphaltAnimationIdle
	dw IngrovertAnimationIdle
	dw FriteshadeAnimationIdle
	dw BugglarAnimationIdle
	dw SpydarAnimationIdle
	dw PorcelionAnimationIdle
	dw FuumaAnimationIdle
	dw WallopyAnimationIdle
	dw JabarooAnimationIdle
	dw OrizuruAnimationIdle
	dw OrigeronAnimationIdle
	dw BinarsAnimationIdle
	dw BushidudeAnimationIdle
	dw SinistarAnimationIdle
	dw DronnelAnimationIdle
	dw RumblebeeAnimationIdle
	dw BagroundAnimationIdle
	dw TerragerAnimationIdle
	dw CauldegarAnimationIdle
	dw RockadeAnimationIdle
	dw BarrockAnimationIdle
	dw MarblockAnimationIdle
	dw SliverfishAnimationIdle
	dw ReddotAnimationIdle
	dw PolkapixAnimationIdle
	dw ImpanAnimationIdle
	dw DaetyrAnimationIdle
	dw DaemoonAnimationIdle
	dw SabarinthAnimationIdle
	dw BombardleAnimationIdle
	dw AntennianAnimationIdle
	dw OkapsiAnimationIdle
	dw TelekapiAnimationIdle
	dw KaiyakAnimationIdle
	dw SurfalloAnimationIdle
	dw HemogoblinAnimationIdle
	dw PlatapoxAnimationIdle
	dw PlatyrusAnimationIdle
	dw SearlingAnimationIdle
	dw FlaribouAnimationIdle
	dw MarskratAnimationIdle
	dw CatybaraAnimationIdle
	dw CrescaldoAnimationIdle
	dw PescaldoAnimationIdle
	dw PlumplingAnimationIdle
	dw LeapearAnimationIdle
	dw LeviathornAnimationIdle
	dw StrawrbleAnimationIdle
	dw StrawmerriAnimationIdle
	dw StrawmenadAnimationIdle
	dw PampoochSAnimationIdle
	dw PampodourSAnimationIdle
	dw PampoochPAnimationIdle
	dw PampodourPAnimationIdle
	dw PampoochTAnimationIdle
	dw PampodourTAnimationIdle
	dw TutsweetAnimationIdle
	dw TutufruttiAnimationIdle
	dw ScrumshefAnimationIdle
	dw SousfleAnimationIdle
	dw ApasheeAnimationIdle
	dw CommansheeAnimationIdle
	dw DittoAnimationIdle
	dw ConstaboldAnimationIdle
	dw TarotisAnimationIdle
	dw OrchantisAnimationIdle
	dw HocupocusAnimationIdle
	dw PresticianAnimationIdle
	dw DoracleAnimationIdle
	dw DelphoraAnimationIdle
	dw XsailerateAnimationIdle
	dw DiviperAnimationIdle
	dw SnorcobraAnimationIdle
	dw EspungeAnimationIdle
	dw ZiggrathAnimationIdle
	dw CanvalogAnimationIdle
	dw PlasmanianAnimationIdle
	dw CladilloAnimationIdle
	dw ArmordilloAnimationIdle
	dw CloakroakAnimationIdle
	dw CamoufraugAnimationIdle
	dw MirauggerAnimationIdle
	dw TrubbleAnimationIdle
	dw GolgraniteAnimationIdle
	dw SwinedelAnimationIdle
	dw ColomentalAnimationIdle
	dw ElecmentalAnimationIdle
	dw OccumentalAnimationIdle
	dw SedimentalAnimationIdle
	dw GaiamentalAnimationIdle
	dw IgnimentalAnimationIdle
	dw MolumentalAnimationIdle
	dw VilementalAnimationIdle
	dw AlumentalAnimationIdle
	dw SalamentalAnimationIdle
	dw FarimentalAnimationIdle
	dw CtrlbotAnimationIdle
	dw AltbotAnimationIdle
	dw DelbotAnimationIdle
	dw PummatAnimationIdle
	dw TraumatAnimationIdle
	dw AcromatAnimationIdle
	dw ParagodaAnimationIdle
	dw DoomstoneAnimationIdle
	dw FeartressAnimationIdle
	dw GothedralAnimationIdle
	dw TsukimikoAnimationIdle
	dw ZonbiAnimationIdle
	dw SmokaiAnimationIdle
	dw TrollgoreAnimationIdle
	dw GexelAnimationIdle
	dw RenderexeAnimationIdle
	dw SuniataAnimationIdle
	dw HapsukaAnimationIdle
	dw DardukaAnimationIdle
	dw StoatsdoolAnimationIdle
	dw ManifistAnimationIdle
	dw GhauntedAnimationIdle
	dw HazvatAnimationIdle
	dw ToxivatAnimationIdle
	dw NarburrAnimationIdle
	dw NarcicleAnimationIdle
	dw PlanktoonAnimationIdle
	dw AguamarineAnimationIdle
	dw CiriousAnimationIdle
	dw ZephluffAnimationIdle
	dw NimbillowAnimationIdle
	dw FafnareAnimationIdle
	dw DreigloreAnimationIdle
	dw BambootemAnimationIdle
	dw FlorascentAnimationIdle
	dw ThissileAnimationIdle
	dw MareepAnimationIdle
	dw FlaaffyAnimationIdle
	dw AmpharosAnimationIdle
	dw BellossomAnimationIdle
	dw MarillAnimationIdle
	dw AzumarillAnimationIdle
	dw SudowoodoAnimationIdle
	dw PolitoedAnimationIdle
	dw HoppipAnimationIdle
	dw SkiploomAnimationIdle
	dw JumpluffAnimationIdle
	dw AipomAnimationIdle
	dw SunkernAnimationIdle
	dw SunfloraAnimationIdle
	dw YanmaAnimationIdle
	dw WooperAnimationIdle
	dw QuagsireAnimationIdle
	dw EspeonAnimationIdle
	dw UmbreonAnimationIdle
	dw MurkrowAnimationIdle
	dw SlowkingAnimationIdle
	dw MisdreavusAnimationIdle
	dw UnownAnimationIdle
	dw WobbuffetAnimationIdle
	dw GirafarigAnimationIdle
	dw PinecoAnimationIdle
	dw ForretressAnimationIdle
	dw DunsparceAnimationIdle
	dw GligarAnimationIdle
	dw SteelixAnimationIdle
	dw SnubbullAnimationIdle
	dw GranbullAnimationIdle
	dw QwilfishAnimationIdle
	dw ScizorAnimationIdle
	dw ShuckleAnimationIdle
	dw HeracrossAnimationIdle
	dw SneaselAnimationIdle
	dw TeddiursaAnimationIdle
	dw UrsaringAnimationIdle
	dw SlugmaAnimationIdle
	dw MagcargoAnimationIdle
	dw SwinubAnimationIdle
	dw PiloswineAnimationIdle
	dw CorsolaAnimationIdle
	dw RemoraidAnimationIdle
	dw OctilleryAnimationIdle
	dw DelibirdAnimationIdle
	dw MantineAnimationIdle
	dw SkarmoryAnimationIdle
	dw HoundourAnimationIdle
	dw HoundoomAnimationIdle
	dw KingdraAnimationIdle
	dw PhanpyAnimationIdle
	dw DonphanAnimationIdle
	dw OmanyteAnimationIdle
	dw OmastarAnimationIdle
	dw KabutoAnimationIdle
	dw KabutopsAnimationIdle
	dw HitmontopAnimationIdle
	dw SmoochumAnimationIdle
	dw ElekidAnimationIdle
	dw MagbyAnimationIdle
	dw MiltankAnimationIdle
	dw BlisseyAnimationIdle
	dw RaikouAnimationIdle
	dw EnteiAnimationIdle
	dw SuicuneAnimationIdle
	dw LarvitarAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw LugiaAnimationIdle
	dw HoOhAnimationIdle
	dw CelebiAnimationIdle
	assert_table_length NUM_POKEMON
