AnimationIdlePointers:
	table_width 2, AnimationIdlePointers
	dw SubminoAnimationIdle
	dw SubzillaAnimationIdle
	dw SubzilanteAnimationIdle
	dw GrassnipAnimationIdle
	dw LopsoilAnimationIdle
	dw HaerazorAnimationIdle
	dw CubburnAnimationIdle
	dw CoaldiakAnimationIdle
	dw GrillzlyAnimationIdle
	dw HippourAnimationIdle
	dw DrippourAnimationIdle
	dw HiptorrentAnimationIdle
	dw HamselAnimationIdle
	dw GuinapiAnimationIdle
	dw OpossterAnimationIdle
	dw PossumusAnimationIdle
	dw AxalitlAnimationIdle
	dw AxalotAnimationIdle
	dw HopstotAnimationIdle
	dw LocutsAnimationIdle
	dw ChawpperAnimationIdle
	dw SnolipoliAnimationIdle
	dw CrystalisAnimationIdle
	dw HailothAnimationIdle
	dw TeakbeakAnimationIdle
	dw WoodrillAnimationIdle
	dw FowlletAnimationIdle
	dw FlockshotAnimationIdle
	dw QartridgeAnimationIdle
	dw LouspoutAnimationIdle
	dw ClinchitonAnimationIdle
	dw SkardineAnimationIdle
	dw SkargarosAnimationIdle
	dw SpikidnaAnimationIdle
	dw EchlipseAnimationIdle
	dw EchneedoAnimationIdle
	dw KitteryAnimationIdle
	dw FeliteAnimationIdle
	dw FelectricAnimationIdle
	dw HiszardAnimationIdle
	dw RepvialAnimationIdle
	dw KomodoseAnimationIdle
	dw CursiorAnimationIdle
	dw EnvoilAnimationIdle
	dw NavitarAnimationIdle
	dw SlickreteAnimationIdle
	dw GasphaltAnimationIdle
	dw IngrovertAnimationIdle
	dw FriteshadeAnimationIdle
	dw BugglarAnimationIdle
	dw SpydarAnimationIdle
	dw PorcelionAnimationIdle
	dw FuumaAnimationIdle
	dw WallopyAnimationIdle
	dw JabarooAnimationIdle
	dw OrizuruAnimationIdle
	dw OrigeronAnimationIdle
	dw BinarsAnimationIdle
	dw BushidudeAnimationIdle
	dw SinistarAnimationIdle
	dw DronnelAnimationIdle
	dw RumblebeeAnimationIdle
	dw BagroundAnimationIdle
	dw TerragerAnimationIdle
	dw CauldegarAnimationIdle
	dw RockadeAnimationIdle
	dw BarrockAnimationIdle
	dw MarblockAnimationIdle
	dw SliverfishAnimationIdle
	dw ReddotAnimationIdle
	dw PolkapixAnimationIdle
	dw ImpanAnimationIdle
	dw DaetyrAnimationIdle
	dw DaemoonAnimationIdle
	dw SabarinthAnimationIdle
	dw BombardleAnimationIdle
	dw AntennianAnimationIdle
	dw OkapsiAnimationIdle
	dw TelekapiAnimationIdle
	dw KaiyakAnimationIdle
	dw SurfalloAnimationIdle
	dw HemogoblinAnimationIdle
	dw PlatapoxAnimationIdle
	dw PlatyrusAnimationIdle
	dw SearlingAnimationIdle
	dw FlaribouAnimationIdle
	dw MarskratAnimationIdle
	dw CatybaraAnimationIdle
	dw CrescaldoAnimationIdle
	dw PescaldoAnimationIdle
	dw PlumplingAnimationIdle
	dw LeapearAnimationIdle
	dw LeviathornAnimationIdle
	dw StrawrbleAnimationIdle
	dw StrawmerriAnimationIdle
	dw StrawmenadAnimationIdle
	dw PampoochSAnimationIdle
	dw PampodourSAnimationIdle
	dw PampoochPAnimationIdle
	dw PampodourPAnimationIdle
	dw PampoochTAnimationIdle
	dw PampodourTAnimationIdle
	dw ExeggutorAnimationIdle
	dw ElectrodeAnimationIdle
	dw MarowakAnimationIdle
	dw HitmonleeAnimationIdle
	dw HitmonchanAnimationIdle
	dw LickitungAnimationIdle
	dw DittoAnimationIdle
	dw WeezingAnimationIdle
	dw RhyhornAnimationIdle
	dw RhydonAnimationIdle
	dw ChanseyAnimationIdle
	dw TangelaAnimationIdle
	dw KangaskhanAnimationIdle
	dw HorseaAnimationIdle
	dw SeadraAnimationIdle
	dw GoldeenAnimationIdle
	dw SeakingAnimationIdle
	dw StaryuAnimationIdle
	dw StarmieAnimationIdle
	dw MrMimeAnimationIdle
	dw ScytherAnimationIdle
	dw JynxAnimationIdle
	dw ElectabuzzAnimationIdle
	dw MagmarAnimationIdle
	dw PinsirAnimationIdle
	dw TaurosAnimationIdle
	dw MagikarpAnimationIdle
	dw GyaradosAnimationIdle
	dw LaprasAnimationIdle
	dw KoffingAnimationIdle
	dw EeveeAnimationIdle
	dw VaporeonAnimationIdle
	dw JolteonAnimationIdle
	dw FlareonAnimationIdle
	dw PorygonAnimationIdle
	dw OmanyteAnimationIdle
	dw OmastarAnimationIdle
	dw KabutoAnimationIdle
	dw KabutopsAnimationIdle
	dw AerodactylAnimationIdle
	dw SnorlaxAnimationIdle
	dw ArticunoAnimationIdle
	dw ZapdosAnimationIdle
	dw MoltresAnimationIdle
	dw DratiniAnimationIdle
	dw DragonairAnimationIdle
	dw DragoniteAnimationIdle
	dw MewtwoAnimationIdle
	dw MewAnimationIdle
	dw ChikoritaAnimationIdle
	dw BayleefAnimationIdle
	dw MeganiumAnimationIdle
	dw CyndaquilAnimationIdle
	dw QuilavaAnimationIdle
	dw TyphlosionAnimationIdle
	dw TotodileAnimationIdle
	dw CroconawAnimationIdle
	dw FeraligatrAnimationIdle
	dw SentretAnimationIdle
	dw FurretAnimationIdle
	dw HoothootAnimationIdle
	dw NoctowlAnimationIdle
	dw LedybaAnimationIdle
	dw LedianAnimationIdle
	dw SpinarakAnimationIdle
	dw AriadosAnimationIdle
	dw CrobatAnimationIdle
	dw ChinchouAnimationIdle
	dw LanturnAnimationIdle
	dw PichuAnimationIdle
	dw CleffaAnimationIdle
	dw IgglybuffAnimationIdle
	dw TogepiAnimationIdle
	dw TogeticAnimationIdle
	dw NatuAnimationIdle
	dw XatuAnimationIdle
	dw MareepAnimationIdle
	dw FlaaffyAnimationIdle
	dw AmpharosAnimationIdle
	dw BellossomAnimationIdle
	dw MarillAnimationIdle
	dw AzumarillAnimationIdle
	dw SudowoodoAnimationIdle
	dw PolitoedAnimationIdle
	dw HoppipAnimationIdle
	dw SkiploomAnimationIdle
	dw JumpluffAnimationIdle
	dw AipomAnimationIdle
	dw SunkernAnimationIdle
	dw SunfloraAnimationIdle
	dw YanmaAnimationIdle
	dw WooperAnimationIdle
	dw QuagsireAnimationIdle
	dw EspeonAnimationIdle
	dw UmbreonAnimationIdle
	dw MurkrowAnimationIdle
	dw SlowkingAnimationIdle
	dw MisdreavusAnimationIdle
	dw UnownAnimationIdle
	dw WobbuffetAnimationIdle
	dw GirafarigAnimationIdle
	dw PinecoAnimationIdle
	dw ForretressAnimationIdle
	dw DunsparceAnimationIdle
	dw GligarAnimationIdle
	dw SteelixAnimationIdle
	dw SnubbullAnimationIdle
	dw GranbullAnimationIdle
	dw QwilfishAnimationIdle
	dw ScizorAnimationIdle
	dw ShuckleAnimationIdle
	dw HeracrossAnimationIdle
	dw SneaselAnimationIdle
	dw TeddiursaAnimationIdle
	dw UrsaringAnimationIdle
	dw SlugmaAnimationIdle
	dw MagcargoAnimationIdle
	dw SwinubAnimationIdle
	dw PiloswineAnimationIdle
	dw CorsolaAnimationIdle
	dw RemoraidAnimationIdle
	dw OctilleryAnimationIdle
	dw DelibirdAnimationIdle
	dw MantineAnimationIdle
	dw SkarmoryAnimationIdle
	dw HoundourAnimationIdle
	dw HoundoomAnimationIdle
	dw KingdraAnimationIdle
	dw PhanpyAnimationIdle
	dw DonphanAnimationIdle
	dw Porygon2AnimationIdle
	dw StantlerAnimationIdle
	dw SmeargleAnimationIdle
	dw TyrogueAnimationIdle
	dw HitmontopAnimationIdle
	dw SmoochumAnimationIdle
	dw ElekidAnimationIdle
	dw MagbyAnimationIdle
	dw MiltankAnimationIdle
	dw BlisseyAnimationIdle
	dw RaikouAnimationIdle
	dw EnteiAnimationIdle
	dw SuicuneAnimationIdle
	dw LarvitarAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw LugiaAnimationIdle
	dw HoOhAnimationIdle
	dw CelebiAnimationIdle
	assert_table_length NUM_POKEMON
