INCLUDE "constants.asm"


; PokemonPicPointers and UnownPicPointers are assumed to start at the same
; address, but in different banks. This is enforced in layout.link.


SECTION "Pic Pointers", ROMX

INCLUDE "data/pokemon/pic_pointers.asm"


SECTION "Unown Pic Pointers", ROMX

INCLUDE "data/pokemon/unown_pic_pointers.asm"


SECTION "Trainer Pic Pointers", ROMX

INCLUDE "data/trainers/pic_pointers.asm"


SECTION "Pics 1", ROMX

HoOhFrontpic:        INCBIN "gfx/pokemon/ho_oh/front.animated.2bpp.lz"
MarblockFrontpic:     INCBIN "gfx/pokemon/marblock/front.animated.2bpp.lz"
FeliteFrontpic:   INCBIN "gfx/pokemon/felite/front.animated.2bpp.lz"
HapsukaFrontpic:  INCBIN "gfx/pokemon/hapsuka/front.animated.2bpp.lz"
SpikidnaFrontpic:    INCBIN "gfx/pokemon/spikidna/front.animated.2bpp.lz"
RaikouFrontpic:      INCBIN "gfx/pokemon/raikou/front.animated.2bpp.lz"
LugiaFrontpic:       INCBIN "gfx/pokemon/lugia/front.animated.2bpp.lz"
AltbotFrontpic:    INCBIN "gfx/pokemon/altbot/front.animated.2bpp.lz"
MirauggerFrontpic:      INCBIN "gfx/pokemon/miraugger/front.animated.2bpp.lz"
SubzilanteFrontpic:  INCBIN "gfx/pokemon/subzilante/front.animated.2bpp.lz"
EnteiFrontpic:       INCBIN "gfx/pokemon/entei/front.animated.2bpp.lz"
SuicuneFrontpic:     INCBIN "gfx/pokemon/suicune/front.animated.2bpp.lz"
GexelFrontpic:  INCBIN "gfx/pokemon/gexel/front.animated.2bpp.lz"


SECTION "Pics 2", ROMX

GrillzlyFrontpic:   INCBIN "gfx/pokemon/grillzly/front.animated.2bpp.lz"
OkapsiFrontpic:    INCBIN "gfx/pokemon/okapsi/front.animated.2bpp.lz"
ZonbiFrontpic:    INCBIN "gfx/pokemon/zonbi/front.animated.2bpp.lz"
ClinchitonFrontpic:   INCBIN "gfx/pokemon/clinchiton/front.animated.2bpp.lz"
SousfleFrontpic:   INCBIN "gfx/pokemon/sousfle/front.animated.2bpp.lz"
ScizorFrontpic:      INCBIN "gfx/pokemon/scizor/front.animated.2bpp.lz"
OpossterFrontpic:    INCBIN "gfx/pokemon/oposster/front.animated.2bpp.lz"
BushidudeFrontpic:    INCBIN "gfx/pokemon/bushidude/front.animated.2bpp.lz"
TyranitarFrontpic:   INCBIN "gfx/pokemon/tyranitar/front.animated.2bpp.lz"
PummatFrontpic:     INCBIN "gfx/pokemon/pummat/front.animated.2bpp.lz"
DelbotFrontpic:      INCBIN "gfx/pokemon/delbot/front.animated.2bpp.lz"
HailothFrontpic:       INCBIN "gfx/pokemon/hailoth/front.animated.2bpp.lz"
DoomstoneFrontpic:      INCBIN "gfx/pokemon/doomstone/front.animated.2bpp.lz"
SnolipoliFrontpic:      INCBIN "gfx/pokemon/snolipoli/front.animated.2bpp.lz"
HaerazorFrontpic:   INCBIN "gfx/pokemon/haerazor/front.animated.2bpp.lz"
TrollgoreFrontpic:     INCBIN "gfx/pokemon/trollgore/front.animated.2bpp.lz"


SECTION "Pics 3", ROMX

SteelixFrontpic:     INCBIN "gfx/pokemon/steelix/front.animated.2bpp.lz"
CauldegarFrontpic:    INCBIN "gfx/pokemon/cauldegar/front.animated.2bpp.lz"
GolgraniteFrontpic:    INCBIN "gfx/pokemon/golgranite/front.animated.2bpp.lz"
DoracleFrontpic:  INCBIN "gfx/pokemon/doracle/front.animated.2bpp.lz"
OrchantisFrontpic:      INCBIN "gfx/pokemon/orchantis/front.animated.2bpp.lz"
JabarooFrontpic:     INCBIN "gfx/pokemon/jabaroo/front.animated.2bpp.lz"
TarotisFrontpic:     INCBIN "gfx/pokemon/tarotis/front.animated.2bpp.lz"
AxalotFrontpic:     INCBIN "gfx/pokemon/axalot/front.animated.2bpp.lz"
KaiyakFrontpic:     INCBIN "gfx/pokemon/kaiyak/front.animated.2bpp.lz"
HiptorrentFrontpic:  INCBIN "gfx/pokemon/hiptorrent/front.animated.2bpp.lz"
ConstaboldFrontpic:     INCBIN "gfx/pokemon/constabold/front.animated.2bpp.lz"
PlumplingFrontpic:    INCBIN "gfx/pokemon/plumpling/front.animated.2bpp.lz"
SkarmoryFrontpic:    INCBIN "gfx/pokemon/skarmory/front.animated.2bpp.lz"
MarskratFrontpic:     INCBIN "gfx/pokemon/marskrat/front.animated.2bpp.lz"
PolkapixFrontpic:  INCBIN "gfx/pokemon/polkapix/front.animated.2bpp.lz"
WoodrillFrontpic:      INCBIN "gfx/pokemon/woodrill/front.animated.2bpp.lz"
OrigeronFrontpic:    INCBIN "gfx/pokemon/origeron/front.animated.2bpp.lz"
OmastarBackpic:      INCBIN "gfx/pokemon/omastar/back.2bpp.lz"


SECTION "Pics 4", ROMX

SearlingFrontpic:      INCBIN "gfx/pokemon/searling/front.animated.2bpp.lz"
SlowkingFrontpic:    INCBIN "gfx/pokemon/slowking/front.animated.2bpp.lz"
HitmontopFrontpic:   INCBIN "gfx/pokemon/hitmontop/front.animated.2bpp.lz"
StrawmerriFrontpic:        INCBIN "gfx/pokemon/strawmerri/front.animated.2bpp.lz"
BlisseyFrontpic:     INCBIN "gfx/pokemon/blissey/front.animated.2bpp.lz"
BarrockFrontpic:     INCBIN "gfx/pokemon/barrock/front.animated.2bpp.lz"
ParagodaFrontpic:   INCBIN "gfx/pokemon/paragoda/front.animated.2bpp.lz"
RumblebeeFrontpic:   INCBIN "gfx/pokemon/rumblebee/front.animated.2bpp.lz"
PlasmanianFrontpic:     INCBIN "gfx/pokemon/plasmanian/front.animated.2bpp.lz"
FarimentalFrontpic:  INCBIN "gfx/pokemon/farimental/front.animated.2bpp.lz"
SnorcobraFrontpic:     INCBIN "gfx/pokemon/snorcobra/front.animated.2bpp.lz"
CrescaldoFrontpic:         INCBIN "gfx/pokemon/crescaldo/front.animated.2bpp.lz"
SuniataFrontpic:    INCBIN "gfx/pokemon/suniata/front.animated.2bpp.lz"
PampodourTFrontpic:       INCBIN "gfx/pokemon/pampodour_t/front.animated.2bpp.lz"
SkargarosFrontpic:    INCBIN "gfx/pokemon/skargaros/front.animated.2bpp.lz"
FlockshotFrontpic:   INCBIN "gfx/pokemon/flockshot/front.animated.2bpp.lz"
SedimentalFrontpic:     INCBIN "gfx/pokemon/sedimental/front.animated.2bpp.lz"
DonphanFrontpic:     INCBIN "gfx/pokemon/donphan/front.animated.2bpp.lz"
CamoufraugFrontpic:      INCBIN "gfx/pokemon/camoufraug/front.animated.2bpp.lz"
UnownEFrontpic:      INCBIN "gfx/pokemon/unown_e/front.animated.2bpp.lz"


SECTION "Pics 5", ROMX

KomodoseFrontpic:      INCBIN "gfx/pokemon/komodose/front.animated.2bpp.lz"
PampoochPFrontpic:     INCBIN "gfx/pokemon/pampooch_p/front.animated.2bpp.lz"
QartridgeFrontpic:   INCBIN "gfx/pokemon/qartridge/front.animated.2bpp.lz"
MagcargoFrontpic:    INCBIN "gfx/pokemon/magcargo/front.animated.2bpp.lz"
FuumaFrontpic:     INCBIN "gfx/pokemon/fuuma/front.animated.2bpp.lz"
VilementalFrontpic:    INCBIN "gfx/pokemon/vilemental/front.animated.2bpp.lz"
LocutsFrontpic:    INCBIN "gfx/pokemon/locuts/front.animated.2bpp.lz"
FriteshadeFrontpic:    INCBIN "gfx/pokemon/friteshade/front.animated.2bpp.lz"
PolitoedFrontpic:    INCBIN "gfx/pokemon/politoed/front.animated.2bpp.lz"
ArmordilloFrontpic:  INCBIN "gfx/pokemon/armordillo/front.animated.2bpp.lz"
MantineFrontpic:     INCBIN "gfx/pokemon/mantine/front.animated.2bpp.lz"
CommansheeFrontpic:   INCBIN "gfx/pokemon/commanshee/front.animated.2bpp.lz"
KingdraFrontpic:     INCBIN "gfx/pokemon/kingdra/front.animated.2bpp.lz"
LopsoilFrontpic:  INCBIN "gfx/pokemon/lopsoil/front.animated.2bpp.lz"
TerragerFrontpic:     INCBIN "gfx/pokemon/terrager/front.animated.2bpp.lz"
TutsweetFrontpic:   INCBIN "gfx/pokemon/tutsweet/front.animated.2bpp.lz"
LeapearFrontpic:      INCBIN "gfx/pokemon/leapear/front.animated.2bpp.lz"
AzumarillFrontpic:   INCBIN "gfx/pokemon/azumarill/front.animated.2bpp.lz"
GasphaltFrontpic:    INCBIN "gfx/pokemon/gasphalt/front.animated.2bpp.lz"
CanvalogFrontpic:      INCBIN "gfx/pokemon/canvalog/front.animated.2bpp.lz"
HeracrossFrontpic:   INCBIN "gfx/pokemon/heracross/front.animated.2bpp.lz"


SECTION "Pics 6", ROMX

NarcicleFrontpic:     INCBIN "gfx/pokemon/narcicle/front.animated.2bpp.lz"
GhauntedFrontpic:     INCBIN "gfx/pokemon/ghaunted/front.animated.2bpp.lz"
CoaldiakFrontpic:   INCBIN "gfx/pokemon/coaldiak/front.animated.2bpp.lz"
SwinedelFrontpic:      INCBIN "gfx/pokemon/swinedel/front.animated.2bpp.lz"
BombardleFrontpic:       INCBIN "gfx/pokemon/bombardle/front.animated.2bpp.lz"
DronnelFrontpic:   INCBIN "gfx/pokemon/dronnel/front.animated.2bpp.lz"
UrsaringFrontpic:    INCBIN "gfx/pokemon/ursaring/front.animated.2bpp.lz"
HoundoomFrontpic:    INCBIN "gfx/pokemon/houndoom/front.animated.2bpp.lz"
KabutopsFrontpic:    INCBIN "gfx/pokemon/kabutops/front.animated.2bpp.lz"
AmpharosFrontpic:    INCBIN "gfx/pokemon/ampharos/front.animated.2bpp.lz"
LouspoutFrontpic:    INCBIN "gfx/pokemon/louspout/front.animated.2bpp.lz"
GaiamentalFrontpic:     INCBIN "gfx/pokemon/gaiamental/front.animated.2bpp.lz"
PlatapoxFrontpic:   INCBIN "gfx/pokemon/platapox/front.animated.2bpp.lz"
NavitarFrontpic:   INCBIN "gfx/pokemon/navitar/front.animated.2bpp.lz"
TsukimikoFrontpic:     INCBIN "gfx/pokemon/tsukimiko/front.animated.2bpp.lz"
CloakroakFrontpic:      INCBIN "gfx/pokemon/cloakroak/front.animated.2bpp.lz"
DaetyrFrontpic:  INCBIN "gfx/pokemon/daetyr/front.animated.2bpp.lz"
ElekidFrontpic:      INCBIN "gfx/pokemon/elekid/front.animated.2bpp.lz"
JumpluffFrontpic:    INCBIN "gfx/pokemon/jumpluff/front.animated.2bpp.lz"
ScrumshefFrontpic:     INCBIN "gfx/pokemon/scrumshef/front.animated.2bpp.lz"
KitteryFrontpic:      INCBIN "gfx/pokemon/kittery/front.animated.2bpp.lz"
GligarFrontpic:      INCBIN "gfx/pokemon/gligar/front.animated.2bpp.lz"
DunsparceFrontpic:   INCBIN "gfx/pokemon/dunsparce/front.animated.2bpp.lz"


SECTION "Pics 7", ROMX

OccumentalFrontpic:    INCBIN "gfx/pokemon/occumental/front.animated.2bpp.lz"
GirafarigFrontpic:   INCBIN "gfx/pokemon/girafarig/front.animated.2bpp.lz"
StrawmenadFrontpic:     INCBIN "gfx/pokemon/strawmenad/front.animated.2bpp.lz"
SneaselFrontpic:     INCBIN "gfx/pokemon/sneasel/front.animated.2bpp.lz"
BellossomFrontpic:   INCBIN "gfx/pokemon/bellossom/front.animated.2bpp.lz"
CtrlbotFrontpic:     INCBIN "gfx/pokemon/ctrlbot/front.animated.2bpp.lz"
HiszardFrontpic:  INCBIN "gfx/pokemon/hiszard/front.animated.2bpp.lz"
YanmaFrontpic:       INCBIN "gfx/pokemon/yanma/front.animated.2bpp.lz"
AlumentalFrontpic:    INCBIN "gfx/pokemon/alumental/front.animated.2bpp.lz"
EchneedoFrontpic:    INCBIN "gfx/pokemon/echneedo/front.animated.2bpp.lz"
AntennianFrontpic:      INCBIN "gfx/pokemon/antennian/front.animated.2bpp.lz"
MurkrowFrontpic:     INCBIN "gfx/pokemon/murkrow/front.animated.2bpp.lz"
SabarinthFrontpic:    INCBIN "gfx/pokemon/sabarinth/front.animated.2bpp.lz"
ZiggrathFrontpic:     INCBIN "gfx/pokemon/ziggrath/front.animated.2bpp.lz"
AxalitlFrontpic:   INCBIN "gfx/pokemon/axalitl/front.animated.2bpp.lz"
HazvatFrontpic:      INCBIN "gfx/pokemon/hazvat/front.animated.2bpp.lz"
StrawrbleFrontpic:      INCBIN "gfx/pokemon/strawrble/front.animated.2bpp.lz"
OmastarFrontpic:     INCBIN "gfx/pokemon/omastar/front.animated.2bpp.lz"
PiloswineFrontpic:   INCBIN "gfx/pokemon/piloswine/front.animated.2bpp.lz"
SpydarFrontpic:     INCBIN "gfx/pokemon/spydar/front.animated.2bpp.lz"
HemogoblinFrontpic:    INCBIN "gfx/pokemon/hemogoblin/front.animated.2bpp.lz"
AcromatFrontpic:   INCBIN "gfx/pokemon/acromat/front.animated.2bpp.lz"
ForretressFrontpic:  INCBIN "gfx/pokemon/forretress/front.animated.2bpp.lz"
TogeticFrontpic:     INCBIN "gfx/pokemon/togetic/front.animated.2bpp.lz"
DoracleBackpic:   INCBIN "gfx/pokemon/doracle/back.2bpp.lz"


SECTION "Pics 8", ROMX

FlaribouFrontpic:        INCBIN "gfx/pokemon/flaribou/front.animated.2bpp.lz"
PlanktoonFrontpic:      INCBIN "gfx/pokemon/planktoon/front.animated.2bpp.lz"
HocupocusFrontpic:     INCBIN "gfx/pokemon/hocupocus/front.animated.2bpp.lz"
PresticianFrontpic:     INCBIN "gfx/pokemon/prestician/front.animated.2bpp.lz"
SnubbullFrontpic:    INCBIN "gfx/pokemon/snubbull/front.animated.2bpp.lz"
GranbullFrontpic:    INCBIN "gfx/pokemon/granbull/front.animated.2bpp.lz"
MiltankFrontpic:     INCBIN "gfx/pokemon/miltank/front.animated.2bpp.lz"
LeviathornFrontpic:     INCBIN "gfx/pokemon/leviathorn/front.animated.2bpp.lz"
SunfloraFrontpic:    INCBIN "gfx/pokemon/sunflora/front.animated.2bpp.lz"
UmbreonFrontpic:     INCBIN "gfx/pokemon/umbreon/front.animated.2bpp.lz"
GothedralFrontpic:   INCBIN "gfx/pokemon/gothedral/front.animated.2bpp.lz"
DiviperFrontpic:     INCBIN "gfx/pokemon/diviper/front.animated.2bpp.lz"
EspeonFrontpic:      INCBIN "gfx/pokemon/espeon/front.animated.2bpp.lz"
XatuFrontpic:        INCBIN "gfx/pokemon/xatu/front.animated.2bpp.lz"
FeartressFrontpic:         INCBIN "gfx/pokemon/feartress/front.animated.2bpp.lz"
OctilleryFrontpic:   INCBIN "gfx/pokemon/octillery/front.animated.2bpp.lz"
CladilloFrontpic:        INCBIN "gfx/pokemon/cladillo/front.animated.2bpp.lz"
WobbuffetFrontpic:   INCBIN "gfx/pokemon/wobbuffet/front.animated.2bpp.lz"
DelibirdFrontpic:    INCBIN "gfx/pokemon/delibird/front.animated.2bpp.lz"
ToxivatFrontpic:      INCBIN "gfx/pokemon/toxivat/front.animated.2bpp.lz"
EnvoilFrontpic:       INCBIN "gfx/pokemon/envoil/front.animated.2bpp.lz"
FlaaffyFrontpic:     INCBIN "gfx/pokemon/flaaffy/front.animated.2bpp.lz"
SubzillaFrontpic:     INCBIN "gfx/pokemon/subzilla/front.animated.2bpp.lz"
StoatsdoolFrontpic:      INCBIN "gfx/pokemon/stoatsdool/front.animated.2bpp.lz"
SmokaiFrontpic:   INCBIN "gfx/pokemon/smokai/front.animated.2bpp.lz"
ApasheeFrontpic:  INCBIN "gfx/pokemon/apashee/front.animated.2bpp.lz"
QuagsireFrontpic:    INCBIN "gfx/pokemon/quagsire/front.animated.2bpp.lz"


SECTION "Pics 9", ROMX

CrystalisFrontpic:       INCBIN "gfx/pokemon/crystalis/front.animated.2bpp.lz"
SudowoodoFrontpic:   INCBIN "gfx/pokemon/sudowoodo/front.animated.2bpp.lz"
TeakbeakFrontpic:     INCBIN "gfx/pokemon/teakbeak/front.animated.2bpp.lz"
XsailerateFrontpic:      INCBIN "gfx/pokemon/xsailerate/front.animated.2bpp.lz"
MagbyFrontpic:       INCBIN "gfx/pokemon/magby/front.animated.2bpp.lz"
ReddotFrontpic:  INCBIN "gfx/pokemon/reddot/front.animated.2bpp.lz"
RenderexeFrontpic:    INCBIN "gfx/pokemon/renderexe/front.animated.2bpp.lz"
CorsolaFrontpic:     INCBIN "gfx/pokemon/corsola/front.animated.2bpp.lz"
FirebreatherPic:     INCBIN "gfx/trainers/firebreather.2bpp.lz"
RockadeFrontpic:      INCBIN "gfx/pokemon/rockade/front.animated.2bpp.lz"
AguamarineFrontpic:    INCBIN "gfx/pokemon/aguamarine/front.animated.2bpp.lz"
HopstotFrontpic:     INCBIN "gfx/pokemon/hopstot/front.animated.2bpp.lz"
ChampionPic:         INCBIN "gfx/trainers/champion.2bpp.lz"
ChawpperFrontpic:     INCBIN "gfx/pokemon/chawpper/front.animated.2bpp.lz"
TrubbleFrontpic:    INCBIN "gfx/pokemon/trubble/front.animated.2bpp.lz"
GrassnipFrontpic:    INCBIN "gfx/pokemon/grassnip/front.animated.2bpp.lz"
SkardineFrontpic:      INCBIN "gfx/pokemon/skardine/front.animated.2bpp.lz"
BlackbeltTPic:       INCBIN "gfx/trainers/blackbelt_t.2bpp.lz"
BikerPic:            INCBIN "gfx/trainers/biker.2bpp.lz"
PampoochTFrontpic:    INCBIN "gfx/pokemon/pampooch_t/front.animated.2bpp.lz"
IgnimentalFrontpic:     INCBIN "gfx/pokemon/ignimental/front.animated.2bpp.lz"
BrunoPic:            INCBIN "gfx/trainers/bruno.2bpp.lz"
CatybaraFrontpic:      INCBIN "gfx/pokemon/catybara/front.animated.2bpp.lz"
EspungeFrontpic:      INCBIN "gfx/pokemon/espunge/front.animated.2bpp.lz"
HikerPic:            INCBIN "gfx/trainers/hiker.2bpp.lz"
PorcelionFrontpic:      INCBIN "gfx/pokemon/porcelion/front.animated.2bpp.lz"
MolumentalFrontpic:    INCBIN "gfx/pokemon/molumental/front.animated.2bpp.lz"
FowlletFrontpic:   INCBIN "gfx/pokemon/fowllet/front.animated.2bpp.lz"
PampoochSFrontpic:    INCBIN "gfx/pokemon/pampooch_s/front.animated.2bpp.lz"
PossumusFrontpic:      INCBIN "gfx/pokemon/possumus/front.animated.2bpp.lz"
GasphaltBackpic:     INCBIN "gfx/pokemon/gasphalt/back.2bpp.lz"


SECTION "Pics 10", ROMX

MisdreavusFrontpic:  INCBIN "gfx/pokemon/misdreavus/front.animated.2bpp.lz"
HoundourFrontpic:    INCBIN "gfx/pokemon/houndour/front.animated.2bpp.lz"
OrizuruFrontpic:      INCBIN "gfx/pokemon/orizuru/front.animated.2bpp.lz"
CelebiFrontpic:      INCBIN "gfx/pokemon/celebi/front.animated.2bpp.lz"
MediumPic:           INCBIN "gfx/trainers/medium.2bpp.lz"
PinecoFrontpic:      INCBIN "gfx/pokemon/pineco/front.animated.2bpp.lz"
PampodourSFrontpic:      INCBIN "gfx/pokemon/pampodour_s/front.animated.2bpp.lz"
FisherPic:           INCBIN "gfx/trainers/fisher.2bpp.lz"
FelectricFrontpic:  INCBIN "gfx/pokemon/felectric/front.animated.2bpp.lz"
SlickreteFrontpic:       INCBIN "gfx/pokemon/slickrete/front.animated.2bpp.lz"
SpikidnaBackpic:     INCBIN "gfx/pokemon/spikidna/back.2bpp.lz"
PokefanmPic:         INCBIN "gfx/trainers/pokefan_m.2bpp.lz"
BoarderPic:          INCBIN "gfx/trainers/boarder.2bpp.lz"
WallopyFrontpic:     INCBIN "gfx/pokemon/wallopy/front.animated.2bpp.lz"
CubburnFrontpic:    INCBIN "gfx/pokemon/cubburn/front.animated.2bpp.lz"
MarblockBackpic:      INCBIN "gfx/pokemon/marblock/back.2bpp.lz"
ColomentalFrontpic:     INCBIN "gfx/pokemon/colomental/front.animated.2bpp.lz"
IngrovertFrontpic:     INCBIN "gfx/pokemon/ingrovert/front.animated.2bpp.lz"
TutsweetBackpic:    INCBIN "gfx/pokemon/tutsweet/back.2bpp.lz"
CiriousFrontpic:     INCBIN "gfx/pokemon/cirious/front.animated.2bpp.lz"
SalamentalFrontpic:     INCBIN "gfx/pokemon/salamental/front.animated.2bpp.lz"
SkiploomFrontpic:    INCBIN "gfx/pokemon/skiploom/front.animated.2bpp.lz"
MareepFrontpic:      INCBIN "gfx/pokemon/mareep/front.animated.2bpp.lz"
ChuckPic:            INCBIN "gfx/trainers/chuck.2bpp.lz"
ElecmentalFrontpic:       INCBIN "gfx/pokemon/elecmental/front.animated.2bpp.lz"
HiptorrentBackpic:   INCBIN "gfx/pokemon/hiptorrent/back.2bpp.lz"
RepvialFrontpic:       INCBIN "gfx/pokemon/repvial/front.animated.2bpp.lz"
KimonoGirlPic:       INCBIN "gfx/trainers/kimono_girl.2bpp.lz"
CauldegarBackpic:     INCBIN "gfx/pokemon/cauldegar/back.2bpp.lz"
AipomFrontpic:       INCBIN "gfx/pokemon/aipom/front.animated.2bpp.lz"
BagroundFrontpic:        INCBIN "gfx/pokemon/baground/front.animated.2bpp.lz"
HitmontopBackpic:    INCBIN "gfx/pokemon/hitmontop/back.2bpp.lz"
PlumplingBackpic:     INCBIN "gfx/pokemon/plumpling/back.2bpp.lz"
ManifistFrontpic:    INCBIN "gfx/pokemon/manifist/front.animated.2bpp.lz"
UnownFBackpic:       INCBIN "gfx/pokemon/unown_f/back.2bpp.lz"


SECTION "Pics 11", ROMX

SearlingBackpic:       INCBIN "gfx/pokemon/searling/back.2bpp.lz"
EchlipseFrontpic:    INCBIN "gfx/pokemon/echlipse/front.animated.2bpp.lz"
SlugmaFrontpic:      INCBIN "gfx/pokemon/slugma/front.animated.2bpp.lz"
BinarsFrontpic:   INCBIN "gfx/pokemon/binars/front.animated.2bpp.lz"
TelekapiFrontpic:    INCBIN "gfx/pokemon/telekapi/front.animated.2bpp.lz"
SmoochumFrontpic:    INCBIN "gfx/pokemon/smoochum/front.animated.2bpp.lz"
JugglerPic:          INCBIN "gfx/trainers/juggler.2bpp.lz"
MarillFrontpic:      INCBIN "gfx/pokemon/marill/front.animated.2bpp.lz"
GuitaristPic:        INCBIN "gfx/trainers/guitarist.2bpp.lz"
PokefanfPic:         INCBIN "gfx/trainers/pokefan_f.2bpp.lz"
FriteshadeBackpic:     INCBIN "gfx/pokemon/friteshade/back.2bpp.lz"
ClairPic:            INCBIN "gfx/trainers/clair.2bpp.lz"
PokemaniacPic:       INCBIN "gfx/trainers/pokemaniac.2bpp.lz"
OmanyteFrontpic:     INCBIN "gfx/pokemon/omanyte/front.animated.2bpp.lz"
SkierPic:            INCBIN "gfx/trainers/skier.2bpp.lz"
PupitarFrontpic:     INCBIN "gfx/pokemon/pupitar/front.animated.2bpp.lz"
SliverfishFrontpic:  INCBIN "gfx/pokemon/sliverfish/front.animated.2bpp.lz"
PescaldoFrontpic:    INCBIN "gfx/pokemon/pescaldo/front.animated.2bpp.lz"
ImpanFrontpic:   INCBIN "gfx/pokemon/impan/front.animated.2bpp.lz"
NimbillowFrontpic:      INCBIN "gfx/pokemon/nimbillow/front.animated.2bpp.lz"
GolgraniteBackpic:     INCBIN "gfx/pokemon/golgranite/back.2bpp.lz"
FeliteBackpic:    INCBIN "gfx/pokemon/felite/back.2bpp.lz"
YanmaBackpic:        INCBIN "gfx/pokemon/yanma/back.2bpp.lz"
CamoufraugBackpic:       INCBIN "gfx/pokemon/camoufraug/back.2bpp.lz"
LassPic:             INCBIN "gfx/trainers/lass.2bpp.lz"
EchneedoBackpic:     INCBIN "gfx/pokemon/echneedo/back.2bpp.lz"
PlatyrusFrontpic:       INCBIN "gfx/pokemon/platyrus/front.animated.2bpp.lz"
HapsukaBackpic:   INCBIN "gfx/pokemon/hapsuka/back.2bpp.lz"
TraumatFrontpic:     INCBIN "gfx/pokemon/traumat/front.animated.2bpp.lz"
HemogoblinBackpic:     INCBIN "gfx/pokemon/hemogoblin/back.2bpp.lz"
QwilfishFrontpic:    INCBIN "gfx/pokemon/qwilfish/front.animated.2bpp.lz"
SuicuneBackpic:      INCBIN "gfx/pokemon/suicune/back.2bpp.lz"
SlowkingBackpic:     INCBIN "gfx/pokemon/slowking/back.2bpp.lz"
ElekidBackpic:       INCBIN "gfx/pokemon/elekid/back.2bpp.lz"
CelebiBackpic:       INCBIN "gfx/pokemon/celebi/back.2bpp.lz"
PampodourSBackpic:       INCBIN "gfx/pokemon/pampodour_s/back.2bpp.lz"
BugCatcherPic:       INCBIN "gfx/trainers/bug_catcher.2bpp.lz"
CtrlbotBackpic:      INCBIN "gfx/pokemon/ctrlbot/back.2bpp.lz"


SECTION "Pics 12", ROMX

SubzilanteBackpic:     INCBIN "gfx/pokemon/subzilante/back.2bpp.lz"
PummatBackpic:      INCBIN "gfx/pokemon/pummat/back.2bpp.lz"
SunfloraBackpic:     INCBIN "gfx/pokemon/sunflora/back.2bpp.lz"
PhanpyFrontpic:      INCBIN "gfx/pokemon/phanpy/front.animated.2bpp.lz"
OrchantisBackpic:       INCBIN "gfx/pokemon/orchantis/back.2bpp.lz"
LarvitarFrontpic:    INCBIN "gfx/pokemon/larvitar/front.animated.2bpp.lz"
TyranitarBackpic:    INCBIN "gfx/pokemon/tyranitar/back.2bpp.lz"
FlockshotBackpic:    INCBIN "gfx/pokemon/flockshot/back.2bpp.lz"
XsailerateBackpic:       INCBIN "gfx/pokemon/xsailerate/back.2bpp.lz"
TwinsPic:            INCBIN "gfx/trainers/twins.2bpp.lz"
PlatapoxBackpic:    INCBIN "gfx/pokemon/platapox/back.2bpp.lz"
PampoochTBackpic:     INCBIN "gfx/pokemon/pampooch_t/back.2bpp.lz"
HazvatBackpic:       INCBIN "gfx/pokemon/hazvat/back.2bpp.lz"
SmokaiBackpic:    INCBIN "gfx/pokemon/smokai/back.2bpp.lz"
TsukimikoBackpic:      INCBIN "gfx/pokemon/tsukimiko/back.2bpp.lz"
CursiorFrontpic:      INCBIN "gfx/pokemon/cursior/front.animated.2bpp.lz"
OkapsiBackpic:     INCBIN "gfx/pokemon/okapsi/back.2bpp.lz"
PlatyrusBackpic:        INCBIN "gfx/pokemon/platyrus/back.2bpp.lz"
HoppipFrontpic:      INCBIN "gfx/pokemon/hoppip/front.animated.2bpp.lz"
OrizuruBackpic:       INCBIN "gfx/pokemon/orizuru/back.2bpp.lz"
CloakroakBackpic:       INCBIN "gfx/pokemon/cloakroak/back.2bpp.lz"
PampodourTBackpic:        INCBIN "gfx/pokemon/pampodour_t/back.2bpp.lz"
TrollgoreBackpic:      INCBIN "gfx/pokemon/trollgore/back.2bpp.lz"
SuniataBackpic:     INCBIN "gfx/pokemon/suniata/back.2bpp.lz"
FowlletBackpic:    INCBIN "gfx/pokemon/fowllet/back.2bpp.lz"
SailorPic:           INCBIN "gfx/trainers/sailor.2bpp.lz"
BeautyPic:           INCBIN "gfx/trainers/beauty.2bpp.lz"
PescaldoBackpic:     INCBIN "gfx/pokemon/pescaldo/back.2bpp.lz"
RepvialBackpic:        INCBIN "gfx/pokemon/repvial/back.2bpp.lz"
TeddiursaFrontpic:   INCBIN "gfx/pokemon/teddiursa/front.animated.2bpp.lz"
SkardineBackpic:       INCBIN "gfx/pokemon/skardine/back.2bpp.lz"
GruntmPic:           INCBIN "gfx/trainers/grunt_m.2bpp.lz"
EnvoilBackpic:        INCBIN "gfx/pokemon/envoil/back.2bpp.lz"
MagcargoBackpic:     INCBIN "gfx/pokemon/magcargo/back.2bpp.lz"
KabutopsBackpic:     INCBIN "gfx/pokemon/kabutops/back.2bpp.lz"
OpossterBackpic:     INCBIN "gfx/pokemon/oposster/back.2bpp.lz"
BushidudeBackpic:     INCBIN "gfx/pokemon/bushidude/back.2bpp.lz"
GaiamentalBackpic:      INCBIN "gfx/pokemon/gaiamental/back.2bpp.lz"
DiviperBackpic:      INCBIN "gfx/pokemon/diviper/back.2bpp.lz"
SubminoFrontpic:     INCBIN "gfx/pokemon/submino/front.animated.2bpp.lz"
ZiggrathBackpic:      INCBIN "gfx/pokemon/ziggrath/back.2bpp.lz"


SECTION "Pics 13", ROMX

OmanyteBackpic:      INCBIN "gfx/pokemon/omanyte/back.2bpp.lz"
PossumusBackpic:       INCBIN "gfx/pokemon/possumus/back.2bpp.lz"
ScientistPic:        INCBIN "gfx/trainers/scientist.2bpp.lz"
QwilfishBackpic:     INCBIN "gfx/pokemon/qwilfish/back.2bpp.lz"
GligarBackpic:       INCBIN "gfx/pokemon/gligar/back.2bpp.lz"
GexelBackpic:   INCBIN "gfx/pokemon/gexel/back.2bpp.lz"
LopsoilBackpic:   INCBIN "gfx/pokemon/lopsoil/back.2bpp.lz"
ClinchitonBackpic:    INCBIN "gfx/pokemon/clinchiton/back.2bpp.lz"
ZephluffFrontpic:       INCBIN "gfx/pokemon/zephluff/front.animated.2bpp.lz"
ArmordilloBackpic:   INCBIN "gfx/pokemon/armordillo/back.2bpp.lz"
ToxivatBackpic:       INCBIN "gfx/pokemon/toxivat/back.2bpp.lz"
PupitarBackpic:      INCBIN "gfx/pokemon/pupitar/back.2bpp.lz"
HeracrossBackpic:    INCBIN "gfx/pokemon/heracross/back.2bpp.lz"
UnownDFrontpic:      INCBIN "gfx/pokemon/unown_d/front.animated.2bpp.lz"
MiltankBackpic:      INCBIN "gfx/pokemon/miltank/back.2bpp.lz"
SteelixBackpic:      INCBIN "gfx/pokemon/steelix/back.2bpp.lz"
FuumaBackpic:      INCBIN "gfx/pokemon/fuuma/back.2bpp.lz"
LtSurgePic:          INCBIN "gfx/trainers/lt_surge.2bpp.lz"
TeacherPic:          INCBIN "gfx/trainers/teacher.2bpp.lz"
EggPic:              INCBIN "gfx/pokemon/egg/front.animated.2bpp.lz"
ElecmentalBackpic:        INCBIN "gfx/pokemon/elecmental/back.2bpp.lz"
ShuckleFrontpic:     INCBIN "gfx/pokemon/shuckle/front.animated.2bpp.lz"
AntennianBackpic:       INCBIN "gfx/pokemon/antennian/back.2bpp.lz"
RemoraidFrontpic:    INCBIN "gfx/pokemon/remoraid/front.animated.2bpp.lz"
SinistarFrontpic:     INCBIN "gfx/pokemon/sinistar/front.animated.2bpp.lz"
StrawmerriBackpic:         INCBIN "gfx/pokemon/strawmerri/back.2bpp.lz"
ColomentalBackpic:      INCBIN "gfx/pokemon/colomental/back.2bpp.lz"
BirdKeeperPic:       INCBIN "gfx/trainers/bird_keeper.2bpp.lz"
FalknerPic:          INCBIN "gfx/trainers/falkner.2bpp.lz"
KarenPic:            INCBIN "gfx/trainers/karen.2bpp.lz"
LouspoutBackpic:     INCBIN "gfx/pokemon/louspout/back.2bpp.lz"
DaetyrBackpic:   INCBIN "gfx/pokemon/daetyr/back.2bpp.lz"
BinarsBackpic:    INCBIN "gfx/pokemon/binars/back.2bpp.lz"
KogaPic:             INCBIN "gfx/trainers/koga.2bpp.lz"
BarrockBackpic:      INCBIN "gfx/pokemon/barrock/back.2bpp.lz"
WoodrillBackpic:       INCBIN "gfx/pokemon/woodrill/back.2bpp.lz"
RumblebeeBackpic:    INCBIN "gfx/pokemon/rumblebee/back.2bpp.lz"
SwimmermPic:         INCBIN "gfx/trainers/swimmer_m.2bpp.lz"
SunkernFrontpic:     INCBIN "gfx/pokemon/sunkern/front.animated.2bpp.lz"
SkargarosBackpic:     INCBIN "gfx/pokemon/skargaros/back.2bpp.lz"
MysticalmanPic:      INCBIN "gfx/trainers/mysticalman.2bpp.lz"
CooltrainerfPic:     INCBIN "gfx/trainers/cooltrainer_f.2bpp.lz"
TutufruttiFrontpic:   INCBIN "gfx/pokemon/tutufrutti/front.animated.2bpp.lz"


SECTION "Pics 14", ROMX

SudowoodoBackpic:    INCBIN "gfx/pokemon/sudowoodo/back.2bpp.lz"
FlaaffyBackpic:      INCBIN "gfx/pokemon/flaaffy/back.2bpp.lz"
DardukaFrontpic:     INCBIN "gfx/pokemon/darduka/front.animated.2bpp.lz"
TogeticBackpic:      INCBIN "gfx/pokemon/togetic/back.2bpp.lz"
BugsyPic:            INCBIN "gfx/trainers/bugsy.2bpp.lz"
ScrumshefBackpic:      INCBIN "gfx/pokemon/scrumshef/back.2bpp.lz"
DaemoonBackpic:      INCBIN "gfx/pokemon/daemoon/back.2bpp.lz"
PlasmanianBackpic:      INCBIN "gfx/pokemon/plasmanian/back.2bpp.lz"
NavitarBackpic:    INCBIN "gfx/pokemon/navitar/back.2bpp.lz"
ApasheeBackpic:   INCBIN "gfx/pokemon/apashee/back.2bpp.lz"
JumpluffBackpic:     INCBIN "gfx/pokemon/jumpluff/back.2bpp.lz"
CooltrainermPic:     INCBIN "gfx/trainers/cooltrainer_m.2bpp.lz"
GrillzlyBackpic:    INCBIN "gfx/pokemon/grillzly/back.2bpp.lz"
MisdreavusBackpic:   INCBIN "gfx/pokemon/misdreavus/back.2bpp.lz"
SalamentalBackpic:      INCBIN "gfx/pokemon/salamental/back.2bpp.lz"
DaemoonFrontpic:     INCBIN "gfx/pokemon/daemoon/front.animated.2bpp.lz"
ScizorBackpic:       INCBIN "gfx/pokemon/scizor/back.2bpp.lz"
GirafarigBackpic:    INCBIN "gfx/pokemon/girafarig/back.2bpp.lz"
VilementalBackpic:     INCBIN "gfx/pokemon/vilemental/back.2bpp.lz"
AlumentalBackpic:     INCBIN "gfx/pokemon/alumental/back.2bpp.lz"
TerragerBackpic:      INCBIN "gfx/pokemon/terrager/back.2bpp.lz"
OrigeronBackpic:     INCBIN "gfx/pokemon/origeron/back.2bpp.lz"
StoatsdoolBackpic:       INCBIN "gfx/pokemon/stoatsdool/back.2bpp.lz"
CoaldiakBackpic:    INCBIN "gfx/pokemon/coaldiak/back.2bpp.lz"
QartridgeBackpic:    INCBIN "gfx/pokemon/qartridge/back.2bpp.lz"
IgglybuffFrontpic:   INCBIN "gfx/pokemon/igglybuff/front.animated.2bpp.lz"
LocutsBackpic:     INCBIN "gfx/pokemon/locuts/back.2bpp.lz"
KitteryBackpic:       INCBIN "gfx/pokemon/kittery/back.2bpp.lz"
CrystalisBackpic:        INCBIN "gfx/pokemon/crystalis/back.2bpp.lz"
SnorcobraBackpic:      INCBIN "gfx/pokemon/snorcobra/back.2bpp.lz"
BurglarPic:          INCBIN "gfx/trainers/burglar.2bpp.lz"
WallopyBackpic:      INCBIN "gfx/pokemon/wallopy/back.2bpp.lz"
TeakbeakBackpic:      INCBIN "gfx/pokemon/teakbeak/back.2bpp.lz"
KabutoFrontpic:      INCBIN "gfx/pokemon/kabuto/front.animated.2bpp.lz"
MareepBackpic:       INCBIN "gfx/pokemon/mareep/back.2bpp.lz"
RemoraidBackpic:     INCBIN "gfx/pokemon/remoraid/back.2bpp.lz"
DittoFrontpic:       INCBIN "gfx/pokemon/ditto/front.animated.2bpp.lz"
KingdraBackpic:      INCBIN "gfx/pokemon/kingdra/back.2bpp.lz"
CamperPic:           INCBIN "gfx/trainers/camper.2bpp.lz"
WooperFrontpic:      INCBIN "gfx/pokemon/wooper/front.animated.2bpp.lz"
EchlipseBackpic:     INCBIN "gfx/pokemon/echlipse/back.2bpp.lz"
IngrovertBackpic:      INCBIN "gfx/pokemon/ingrovert/back.2bpp.lz"
BellossomBackpic:    INCBIN "gfx/pokemon/bellossom/back.2bpp.lz"
Rival1Pic:           INCBIN "gfx/trainers/rival1.2bpp.lz"
SwinubBackpic:       INCBIN "gfx/pokemon/swinub/back.2bpp.lz"


SECTION "Pics 15", ROMX

DoomstoneBackpic:       INCBIN "gfx/pokemon/doomstone/back.2bpp.lz"
PokemonProfPic:      INCBIN "gfx/trainers/oak.2bpp.lz"
CalPic:              INCBIN "gfx/trainers/cal.2bpp.lz"
SwimmerfPic:         INCBIN "gfx/trainers/swimmer_f.2bpp.lz"
BugglarFrontpic:     INCBIN "gfx/pokemon/bugglar/front.animated.2bpp.lz"
OfficerPic:          INCBIN "gfx/trainers/officer.2bpp.lz"
CrescaldoBackpic:          INCBIN "gfx/pokemon/crescaldo/back.2bpp.lz"
DelibirdBackpic:     INCBIN "gfx/pokemon/delibird/back.2bpp.lz"
SabrinaPic:          INCBIN "gfx/trainers/sabrina.2bpp.lz"
TrubbleBackpic:     INCBIN "gfx/pokemon/trubble/back.2bpp.lz"
NarcicleBackpic:      INCBIN "gfx/pokemon/narcicle/back.2bpp.lz"
SneaselBackpic:      INCBIN "gfx/pokemon/sneasel/back.2bpp.lz"
UmbreonBackpic:      INCBIN "gfx/pokemon/umbreon/back.2bpp.lz"
MurkrowBackpic:      INCBIN "gfx/pokemon/murkrow/back.2bpp.lz"
SubzillaBackpic:      INCBIN "gfx/pokemon/subzilla/back.2bpp.lz"
KaiyakBackpic:      INCBIN "gfx/pokemon/kaiyak/back.2bpp.lz"
PsychicTPic:         INCBIN "gfx/trainers/psychic_t.2bpp.lz"
JabarooBackpic:      INCBIN "gfx/pokemon/jabaroo/back.2bpp.lz"
ConstaboldBackpic:      INCBIN "gfx/pokemon/constabold/back.2bpp.lz"
EnteiBackpic:        INCBIN "gfx/pokemon/entei/back.2bpp.lz"
GruntfPic:           INCBIN "gfx/trainers/grunt_f.2bpp.lz"
DelphoraFrontpic:      INCBIN "gfx/pokemon/delphora/front.animated.2bpp.lz"
AxalotBackpic:      INCBIN "gfx/pokemon/axalot/back.2bpp.lz"
HoOhBackpic:         INCBIN "gfx/pokemon/ho_oh/back.2bpp.lz"
DronnelBackpic:    INCBIN "gfx/pokemon/dronnel/back.2bpp.lz"
FeartressBackpic:          INCBIN "gfx/pokemon/feartress/back.2bpp.lz"
RockadeBackpic:       INCBIN "gfx/pokemon/rockade/back.2bpp.lz"
BagroundBackpic:         INCBIN "gfx/pokemon/baground/back.2bpp.lz"
FarimentalBackpic:   INCBIN "gfx/pokemon/farimental/back.2bpp.lz"
GuinapiFrontpic:      INCBIN "gfx/pokemon/guinapi/front.animated.2bpp.lz"
SpydarBackpic:      INCBIN "gfx/pokemon/spydar/back.2bpp.lz"
ReddotBackpic:   INCBIN "gfx/pokemon/reddot/back.2bpp.lz"
PampoochSBackpic:     INCBIN "gfx/pokemon/pampooch_s/back.2bpp.lz"
SabarinthBackpic:     INCBIN "gfx/pokemon/sabarinth/back.2bpp.lz"
AipomBackpic:        INCBIN "gfx/pokemon/aipom/back.2bpp.lz"
EspeonBackpic:       INCBIN "gfx/pokemon/espeon/back.2bpp.lz"
HamselFrontpic:      INCBIN "gfx/pokemon/hamsel/front.animated.2bpp.lz"
RenderexeBackpic:     INCBIN "gfx/pokemon/renderexe/back.2bpp.lz"
SnubbullBackpic:     INCBIN "gfx/pokemon/snubbull/back.2bpp.lz"
PampoochPBackpic:      INCBIN "gfx/pokemon/pampooch_p/back.2bpp.lz"
StrawrbleBackpic:       INCBIN "gfx/pokemon/strawrble/back.2bpp.lz"
HopstotBackpic:      INCBIN "gfx/pokemon/hopstot/back.2bpp.lz"
YoungsterPic:        INCBIN "gfx/trainers/youngster.2bpp.lz"
WillPic:             INCBIN "gfx/trainers/will.2bpp.lz"
SchoolboyPic:        INCBIN "gfx/trainers/schoolboy.2bpp.lz"
SurfalloFrontpic:   INCBIN "gfx/pokemon/surfallo/front.animated.2bpp.lz"
SurfalloBackpic:    INCBIN "gfx/pokemon/surfallo/back.2bpp.lz"


SECTION "Pics 16", ROMX

ManifistBackpic:     INCBIN "gfx/pokemon/manifist/back.2bpp.lz"
GhauntedBackpic:      INCBIN "gfx/pokemon/ghaunted/back.2bpp.lz"
SlugmaBackpic:       INCBIN "gfx/pokemon/slugma/back.2bpp.lz"
KabutoBackpic:       INCBIN "gfx/pokemon/kabuto/back.2bpp.lz"
PolkapixBackpic:   INCBIN "gfx/pokemon/polkapix/back.2bpp.lz"
PorcelionBackpic:       INCBIN "gfx/pokemon/porcelion/back.2bpp.lz"
ZonbiBackpic:     INCBIN "gfx/pokemon/zonbi/back.2bpp.lz"
PicnickerPic:        INCBIN "gfx/trainers/picnicker.2bpp.lz"
CommansheeBackpic:    INCBIN "gfx/pokemon/commanshee/back.2bpp.lz"
TogepiFrontpic:      INCBIN "gfx/pokemon/togepi/front.animated.2bpp.lz"
SuperNerdPic:        INCBIN "gfx/trainers/super_nerd.2bpp.lz"
LeviathornBackpic:      INCBIN "gfx/pokemon/leviathorn/back.2bpp.lz"
XatuBackpic:         INCBIN "gfx/pokemon/xatu/back.2bpp.lz"
MolumentalBackpic:     INCBIN "gfx/pokemon/molumental/back.2bpp.lz"
PinecoBackpic:       INCBIN "gfx/pokemon/pineco/back.2bpp.lz"
DrippourFrontpic:     INCBIN "gfx/pokemon/drippour/front.animated.2bpp.lz"
FlaribouBackpic:         INCBIN "gfx/pokemon/flaribou/back.2bpp.lz"
QuagsireBackpic:     INCBIN "gfx/pokemon/quagsire/back.2bpp.lz"
WhitneyPic:          INCBIN "gfx/trainers/whitney.2bpp.lz"
SedimentalBackpic:      INCBIN "gfx/pokemon/sedimental/back.2bpp.lz"
HippourFrontpic:    INCBIN "gfx/pokemon/hippour/front.animated.2bpp.lz"
HoppipBackpic:       INCBIN "gfx/pokemon/hoppip/back.2bpp.lz"
GranbullBackpic:     INCBIN "gfx/pokemon/granbull/back.2bpp.lz"
GentlemanPic:        INCBIN "gfx/trainers/gentleman.2bpp.lz"
ChawpperBackpic:      INCBIN "gfx/pokemon/chawpper/back.2bpp.lz"
SunkernBackpic:      INCBIN "gfx/pokemon/sunkern/back.2bpp.lz"
SwinedelBackpic:       INCBIN "gfx/pokemon/swinedel/back.2bpp.lz"
MagbyBackpic:        INCBIN "gfx/pokemon/magby/back.2bpp.lz"
AcromatBackpic:    INCBIN "gfx/pokemon/acromat/back.2bpp.lz"
DelbotBackpic:       INCBIN "gfx/pokemon/delbot/back.2bpp.lz"
GothedralBackpic:    INCBIN "gfx/pokemon/gothedral/back.2bpp.lz"
CorsolaBackpic:      INCBIN "gfx/pokemon/corsola/back.2bpp.lz"
AguamarineBackpic:     INCBIN "gfx/pokemon/aguamarine/back.2bpp.lz"
HocupocusBackpic:      INCBIN "gfx/pokemon/hocupocus/back.2bpp.lz"
SkiploomBackpic:     INCBIN "gfx/pokemon/skiploom/back.2bpp.lz"
NarburrFrontpic:    INCBIN "gfx/pokemon/narburr/front.animated.2bpp.lz"
Rival2Pic:           INCBIN "gfx/trainers/rival2.2bpp.lz"
UnownWFrontpic:      INCBIN "gfx/pokemon/unown_w/front.animated.2bpp.lz"
TarotisBackpic:      INCBIN "gfx/pokemon/tarotis/back.2bpp.lz"
UnownCFrontpic:      INCBIN "gfx/pokemon/unown_c/front.animated.2bpp.lz"
MistyPic:            INCBIN "gfx/trainers/misty.2bpp.lz"
BlainePic:           INCBIN "gfx/trainers/blaine.2bpp.lz"
UnownZFrontpic:      INCBIN "gfx/pokemon/unown_z/front.animated.2bpp.lz"
SwinubFrontpic:      INCBIN "gfx/pokemon/swinub/front.animated.2bpp.lz"
LarvitarBackpic:     INCBIN "gfx/pokemon/larvitar/back.2bpp.lz"
IgnimentalBackpic:      INCBIN "gfx/pokemon/ignimental/back.2bpp.lz"
UnownHBackpic:       INCBIN "gfx/pokemon/unown_h/back.2bpp.lz"


SECTION "Pics 17", ROMX

SlickreteBackpic:        INCBIN "gfx/pokemon/slickrete/back.2bpp.lz"
OccumentalBackpic:     INCBIN "gfx/pokemon/occumental/back.2bpp.lz"
ImpanBackpic:    INCBIN "gfx/pokemon/impan/back.2bpp.lz"
SubminoBackpic:      INCBIN "gfx/pokemon/submino/back.2bpp.lz"
SmoochumBackpic:     INCBIN "gfx/pokemon/smoochum/back.2bpp.lz"
ZephluffBackpic:        INCBIN "gfx/pokemon/zephluff/back.2bpp.lz"
HoundoomBackpic:     INCBIN "gfx/pokemon/houndoom/back.2bpp.lz"
SliverfishBackpic:   INCBIN "gfx/pokemon/sliverfish/back.2bpp.lz"
CatybaraBackpic:       INCBIN "gfx/pokemon/catybara/back.2bpp.lz"
CiriousBackpic:      INCBIN "gfx/pokemon/cirious/back.2bpp.lz"
AxalitlBackpic:    INCBIN "gfx/pokemon/axalitl/back.2bpp.lz"
EspungeBackpic:       INCBIN "gfx/pokemon/espunge/back.2bpp.lz"
CanvalogBackpic:       INCBIN "gfx/pokemon/canvalog/back.2bpp.lz"
HippourBackpic:     INCBIN "gfx/pokemon/hippour/back.2bpp.lz"
PampodourPFrontpic:     INCBIN "gfx/pokemon/pampodour_p/front.animated.2bpp.lz"
LugiaBackpic:        INCBIN "gfx/pokemon/lugia/back.2bpp.lz"
UnownGFrontpic:      INCBIN "gfx/pokemon/unown_g/front.animated.2bpp.lz"
HailothBackpic:        INCBIN "gfx/pokemon/hailoth/back.2bpp.lz"
PolitoedBackpic:     INCBIN "gfx/pokemon/politoed/back.2bpp.lz"
ParagodaBackpic:    INCBIN "gfx/pokemon/paragoda/back.2bpp.lz"
SousfleBackpic:    INCBIN "gfx/pokemon/sousfle/back.2bpp.lz"
NatuFrontpic:        INCBIN "gfx/pokemon/natu/front.animated.2bpp.lz"
UrsaringBackpic:     INCBIN "gfx/pokemon/ursaring/back.2bpp.lz"
TeddiursaBackpic:    INCBIN "gfx/pokemon/teddiursa/back.2bpp.lz"
PhanpyBackpic:       INCBIN "gfx/pokemon/phanpy/back.2bpp.lz"
UnownVFrontpic:      INCBIN "gfx/pokemon/unown_v/front.animated.2bpp.lz"
GuinapiBackpic:       INCBIN "gfx/pokemon/guinapi/back.2bpp.lz"
WobbuffetBackpic:    INCBIN "gfx/pokemon/wobbuffet/back.2bpp.lz"
TogepiBackpic:       INCBIN "gfx/pokemon/togepi/back.2bpp.lz"
PlanktoonBackpic:       INCBIN "gfx/pokemon/planktoon/back.2bpp.lz"
BlisseyBackpic:      INCBIN "gfx/pokemon/blissey/back.2bpp.lz"
AmpharosBackpic:     INCBIN "gfx/pokemon/ampharos/back.2bpp.lz"
IgglybuffBackpic:    INCBIN "gfx/pokemon/igglybuff/back.2bpp.lz"
AzumarillBackpic:    INCBIN "gfx/pokemon/azumarill/back.2bpp.lz"
OctilleryBackpic:    INCBIN "gfx/pokemon/octillery/back.2bpp.lz"
UnownSFrontpic:      INCBIN "gfx/pokemon/unown_s/front.animated.2bpp.lz"
DelphoraBackpic:       INCBIN "gfx/pokemon/delphora/back.2bpp.lz"
DardukaBackpic:      INCBIN "gfx/pokemon/darduka/back.2bpp.lz"
HiszardBackpic:   INCBIN "gfx/pokemon/hiszard/back.2bpp.lz"
AltbotBackpic:     INCBIN "gfx/pokemon/altbot/back.2bpp.lz"
DittoBackpic:        INCBIN "gfx/pokemon/ditto/back.2bpp.lz"
HamselBackpic:       INCBIN "gfx/pokemon/hamsel/back.2bpp.lz"
UnownHFrontpic:      INCBIN "gfx/pokemon/unown_h/front.animated.2bpp.lz"
NimbillowBackpic:       INCBIN "gfx/pokemon/nimbillow/back.2bpp.lz"
StrawmenadBackpic:      INCBIN "gfx/pokemon/strawmenad/back.2bpp.lz"
LeapearBackpic:       INCBIN "gfx/pokemon/leapear/back.2bpp.lz"
SnolipoliBackpic:       INCBIN "gfx/pokemon/snolipoli/back.2bpp.lz"
MarillBackpic:       INCBIN "gfx/pokemon/marill/back.2bpp.lz"
TraumatBackpic:      INCBIN "gfx/pokemon/traumat/back.2bpp.lz"
TutufruttiBackpic:    INCBIN "gfx/pokemon/tutufrutti/back.2bpp.lz"
SkarmoryBackpic:     INCBIN "gfx/pokemon/skarmory/back.2bpp.lz"
FelectricBackpic:   INCBIN "gfx/pokemon/felectric/back.2bpp.lz"
CursiorBackpic:       INCBIN "gfx/pokemon/cursior/back.2bpp.lz"


SECTION "Pics 18", ROMX

NarburrBackpic:     INCBIN "gfx/pokemon/narburr/back.2bpp.lz"
RaikouBackpic:       INCBIN "gfx/pokemon/raikou/back.2bpp.lz"
UnownKFrontpic:      INCBIN "gfx/pokemon/unown_k/front.animated.2bpp.lz"
HoundourBackpic:     INCBIN "gfx/pokemon/houndour/back.2bpp.lz"
SinistarBackpic:      INCBIN "gfx/pokemon/sinistar/back.2bpp.lz"
CubburnBackpic:     INCBIN "gfx/pokemon/cubburn/back.2bpp.lz"
ShuckleBackpic:      INCBIN "gfx/pokemon/shuckle/back.2bpp.lz"
MarskratBackpic:      INCBIN "gfx/pokemon/marskrat/back.2bpp.lz"
UnownBFrontpic:      INCBIN "gfx/pokemon/unown_b/front.animated.2bpp.lz"
TelekapiBackpic:     INCBIN "gfx/pokemon/telekapi/back.2bpp.lz"
DunsparceBackpic:    INCBIN "gfx/pokemon/dunsparce/back.2bpp.lz"
DonphanBackpic:      INCBIN "gfx/pokemon/donphan/back.2bpp.lz"
WooperBackpic:       INCBIN "gfx/pokemon/wooper/back.2bpp.lz"
MirauggerBackpic:       INCBIN "gfx/pokemon/miraugger/back.2bpp.lz"
UnownXFrontpic:      INCBIN "gfx/pokemon/unown_x/front.animated.2bpp.lz"
UnownNFrontpic:      INCBIN "gfx/pokemon/unown_n/front.animated.2bpp.lz"
PresticianBackpic:      INCBIN "gfx/pokemon/prestician/back.2bpp.lz"
PampodourPBackpic:      INCBIN "gfx/pokemon/pampodour_p/back.2bpp.lz"
UnownJFrontpic:      INCBIN "gfx/pokemon/unown_j/front.animated.2bpp.lz"
MantineBackpic:      INCBIN "gfx/pokemon/mantine/back.2bpp.lz"
UnownLFrontpic:      INCBIN "gfx/pokemon/unown_l/front.animated.2bpp.lz"
PiloswineBackpic:    INCBIN "gfx/pokemon/piloswine/back.2bpp.lz"
UnownMFrontpic:      INCBIN "gfx/pokemon/unown_m/front.animated.2bpp.lz"
UnownFFrontpic:      INCBIN "gfx/pokemon/unown_f/front.animated.2bpp.lz"
NatuBackpic:         INCBIN "gfx/pokemon/natu/back.2bpp.lz"
UnownAFrontpic:      INCBIN "gfx/pokemon/unown_a/front.animated.2bpp.lz"
BombardleBackpic:        INCBIN "gfx/pokemon/bombardle/back.2bpp.lz"
UnownUFrontpic:      INCBIN "gfx/pokemon/unown_u/front.animated.2bpp.lz"
BugglarBackpic:      INCBIN "gfx/pokemon/bugglar/back.2bpp.lz"
UnownQFrontpic:      INCBIN "gfx/pokemon/unown_q/front.animated.2bpp.lz"
UnownPFrontpic:      INCBIN "gfx/pokemon/unown_p/front.animated.2bpp.lz"
UnownCBackpic:       INCBIN "gfx/pokemon/unown_c/back.2bpp.lz"
CladilloBackpic:         INCBIN "gfx/pokemon/cladillo/back.2bpp.lz"
KomodoseBackpic:       INCBIN "gfx/pokemon/komodose/back.2bpp.lz"
UnownYFrontpic:      INCBIN "gfx/pokemon/unown_y/front.animated.2bpp.lz"
UnownGBackpic:       INCBIN "gfx/pokemon/unown_g/back.2bpp.lz"
UnownIFrontpic:      INCBIN "gfx/pokemon/unown_i/front.animated.2bpp.lz"
UnownVBackpic:       INCBIN "gfx/pokemon/unown_v/back.2bpp.lz"
ForretressBackpic:   INCBIN "gfx/pokemon/forretress/back.2bpp.lz"
UnownSBackpic:       INCBIN "gfx/pokemon/unown_s/back.2bpp.lz"
UnownRFrontpic:      INCBIN "gfx/pokemon/unown_r/front.animated.2bpp.lz"
UnownEBackpic:       INCBIN "gfx/pokemon/unown_e/back.2bpp.lz"
UnownJBackpic:       INCBIN "gfx/pokemon/unown_j/back.2bpp.lz"
UnownBBackpic:       INCBIN "gfx/pokemon/unown_b/back.2bpp.lz"
UnownOBackpic:       INCBIN "gfx/pokemon/unown_o/back.2bpp.lz"
UnownZBackpic:       INCBIN "gfx/pokemon/unown_z/back.2bpp.lz"
UnownWBackpic:       INCBIN "gfx/pokemon/unown_w/back.2bpp.lz"
UnownNBackpic:       INCBIN "gfx/pokemon/unown_n/back.2bpp.lz"
UnownABackpic:       INCBIN "gfx/pokemon/unown_a/back.2bpp.lz"
UnownMBackpic:       INCBIN "gfx/pokemon/unown_m/back.2bpp.lz"
UnownKBackpic:       INCBIN "gfx/pokemon/unown_k/back.2bpp.lz"
UnownTBackpic:       INCBIN "gfx/pokemon/unown_t/back.2bpp.lz"
UnownXBackpic:       INCBIN "gfx/pokemon/unown_x/back.2bpp.lz"
UnownLBackpic:       INCBIN "gfx/pokemon/unown_l/back.2bpp.lz"
UnownUBackpic:       INCBIN "gfx/pokemon/unown_u/back.2bpp.lz"
UnownQBackpic:       INCBIN "gfx/pokemon/unown_q/back.2bpp.lz"
UnownYBackpic:       INCBIN "gfx/pokemon/unown_y/back.2bpp.lz"
UnownPBackpic:       INCBIN "gfx/pokemon/unown_p/back.2bpp.lz"
UnownIBackpic:       INCBIN "gfx/pokemon/unown_i/back.2bpp.lz"
UnownRBackpic:       INCBIN "gfx/pokemon/unown_r/back.2bpp.lz"


SECTION "Pics 19", ROMX

; Seems to be an accidental copy of the previous bank

GrassnipBackpic:   INCBIN "gfx/pokemon/grassnip/back.2bpp.lz"
HaerazorBackpic:   INCBIN "gfx/pokemon/haerazor/back.2bpp.lz"
DrippourBackpic:   INCBIN "gfx/pokemon/drippour/back.2bpp.lz"
PrycePic:            INCBIN "gfx/trainers/pryce.2bpp.lz"
BrockPic:            INCBIN "gfx/trainers/brock.2bpp.lz"
MortyPic:            INCBIN "gfx/trainers/morty.2bpp.lz"
ErikaPic:            INCBIN "gfx/trainers/erika.2bpp.lz"
JaninePic:           INCBIN "gfx/trainers/janine.2bpp.lz"
SagePic:             INCBIN "gfx/trainers/sage.2bpp.lz"
RedPic:              INCBIN "gfx/trainers/red.2bpp.lz"
BluePic:             INCBIN "gfx/trainers/blue.2bpp.lz"
ExecutivefPic:       INCBIN "gfx/trainers/executive_f.2bpp.lz"
ExecutivemPic:       INCBIN "gfx/trainers/executive_m.2bpp.lz"
JasminePic:          INCBIN "gfx/trainers/jasmine.2bpp.lz"
INCBIN "gfx/pokemon/unown_n/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/prestician/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_j/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/mantine/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_l/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/piloswine/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_m/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/unown_f/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/natu/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_a/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/bombardle/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_u/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/bugglar/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_q/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/unown_p/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/unown_c/back.2bpp.lz"
INCBIN "gfx/pokemon/cladillo/back.2bpp.lz"
INCBIN "gfx/pokemon/komodose/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_y/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/unown_g/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_i/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/unown_v/back.2bpp.lz"
INCBIN "gfx/pokemon/forretress/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_s/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_r/front.animated.2bpp.lz"
INCBIN "gfx/pokemon/unown_e/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_j/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_b/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_o/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_z/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_w/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_n/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_a/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_m/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_k/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_t/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_x/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_l/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_u/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_q/back.2bpp.lz"
INCBIN "gfx/pokemon/unown_y/back.2bpp.lz"
UnownOFrontpic:      INCBIN "gfx/pokemon/unown_o/front.animated.2bpp.lz"
UnownTFrontpic:      INCBIN "gfx/pokemon/unown_t/front.animated.2bpp.lz"
UnownDBackpic:       INCBIN "gfx/pokemon/unown_d/back.2bpp.lz"


; Sections "Pics 20" to "Pics 24" are not used for any graphics,
; but entries for their banks exist in FixPicBank (see engine/gfx/load_pics.asm).

SECTION "Pics 20", ROMX

SECTION "Pics 21", ROMX

SECTION "Pics 22", ROMX

SECTION "Pics 23", ROMX

SECTION "Pics 24", ROMX
